// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: proto/envoy.proto

package envoy

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 负载均衡策略
type LoadBalancerPolicy int32

const (
	LoadBalancerPolicy_ROUND_ROBIN          LoadBalancerPolicy = 0
	LoadBalancerPolicy_LEAST_CONNECTIONS    LoadBalancerPolicy = 1
	LoadBalancerPolicy_WEIGHTED_ROUND_ROBIN LoadBalancerPolicy = 2
	LoadBalancerPolicy_RANDOM               LoadBalancerPolicy = 3
	LoadBalancerPolicy_CONSISTENT_HASH      LoadBalancerPolicy = 4
)

// Enum value maps for LoadBalancerPolicy.
var (
	LoadBalancerPolicy_name = map[int32]string{
		0: "ROUND_ROBIN",
		1: "LEAST_CONNECTIONS",
		2: "WEIGHTED_ROUND_ROBIN",
		3: "RANDOM",
		4: "CONSISTENT_HASH",
	}
	LoadBalancerPolicy_value = map[string]int32{
		"ROUND_ROBIN":          0,
		"LEAST_CONNECTIONS":    1,
		"WEIGHTED_ROUND_ROBIN": 2,
		"RANDOM":               3,
		"CONSISTENT_HASH":      4,
	}
)

func (x LoadBalancerPolicy) Enum() *LoadBalancerPolicy {
	p := new(LoadBalancerPolicy)
	*p = x
	return p
}

func (x LoadBalancerPolicy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LoadBalancerPolicy) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_envoy_proto_enumTypes[0].Descriptor()
}

func (LoadBalancerPolicy) Type() protoreflect.EnumType {
	return &file_proto_envoy_proto_enumTypes[0]
}

func (x LoadBalancerPolicy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LoadBalancerPolicy.Descriptor instead.
func (LoadBalancerPolicy) EnumDescriptor() ([]byte, []int) {
	return file_proto_envoy_proto_rawDescGZIP(), []int{0}
}

// 注册后端服务请求
type RegisterBackendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"` // xbox-controller, saas-backend
	Endpoint      string                 `protobuf:"bytes,2,opt,name=endpoint,proto3" json:"endpoint,omitempty"`                          // IP:Port
	Weight        int32                  `protobuf:"varint,3,opt,name=weight,proto3" json:"weight,omitempty"`                             // 负载均衡权重
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	HealthCheck   *HealthCheckConfig     `protobuf:"bytes,5,opt,name=health_check,json=healthCheck,proto3" json:"health_check,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterBackendRequest) Reset() {
	*x = RegisterBackendRequest{}
	mi := &file_proto_envoy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterBackendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterBackendRequest) ProtoMessage() {}

func (x *RegisterBackendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_envoy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterBackendRequest.ProtoReflect.Descriptor instead.
func (*RegisterBackendRequest) Descriptor() ([]byte, []int) {
	return file_proto_envoy_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterBackendRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *RegisterBackendRequest) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *RegisterBackendRequest) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *RegisterBackendRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *RegisterBackendRequest) GetHealthCheck() *HealthCheckConfig {
	if x != nil {
		return x.HealthCheck
	}
	return nil
}

// 健康检查配置
type HealthCheckConfig struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Path               string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`                                                        // 健康检查路径，如 /health
	IntervalSeconds    int32                  `protobuf:"varint,2,opt,name=interval_seconds,json=intervalSeconds,proto3" json:"interval_seconds,omitempty"`          // 检查间隔
	TimeoutSeconds     int32                  `protobuf:"varint,3,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`             // 超时时间
	HealthyThreshold   int32                  `protobuf:"varint,4,opt,name=healthy_threshold,json=healthyThreshold,proto3" json:"healthy_threshold,omitempty"`       // 健康阈值
	UnhealthyThreshold int32                  `protobuf:"varint,5,opt,name=unhealthy_threshold,json=unhealthyThreshold,proto3" json:"unhealthy_threshold,omitempty"` // 不健康阈值
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *HealthCheckConfig) Reset() {
	*x = HealthCheckConfig{}
	mi := &file_proto_envoy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckConfig) ProtoMessage() {}

func (x *HealthCheckConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_envoy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckConfig.ProtoReflect.Descriptor instead.
func (*HealthCheckConfig) Descriptor() ([]byte, []int) {
	return file_proto_envoy_proto_rawDescGZIP(), []int{1}
}

func (x *HealthCheckConfig) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *HealthCheckConfig) GetIntervalSeconds() int32 {
	if x != nil {
		return x.IntervalSeconds
	}
	return 0
}

func (x *HealthCheckConfig) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *HealthCheckConfig) GetHealthyThreshold() int32 {
	if x != nil {
		return x.HealthyThreshold
	}
	return 0
}

func (x *HealthCheckConfig) GetUnhealthyThreshold() int32 {
	if x != nil {
		return x.UnhealthyThreshold
	}
	return 0
}

// 注册后端服务响应
type RegisterBackendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	BackendId     string                 `protobuf:"bytes,3,opt,name=backend_id,json=backendId,proto3" json:"backend_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterBackendResponse) Reset() {
	*x = RegisterBackendResponse{}
	mi := &file_proto_envoy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterBackendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterBackendResponse) ProtoMessage() {}

func (x *RegisterBackendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_envoy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterBackendResponse.ProtoReflect.Descriptor instead.
func (*RegisterBackendResponse) Descriptor() ([]byte, []int) {
	return file_proto_envoy_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterBackendResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterBackendResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RegisterBackendResponse) GetBackendId() string {
	if x != nil {
		return x.BackendId
	}
	return ""
}

// 注销后端服务请求
type UnregisterBackendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Endpoint      string                 `protobuf:"bytes,2,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterBackendRequest) Reset() {
	*x = UnregisterBackendRequest{}
	mi := &file_proto_envoy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterBackendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterBackendRequest) ProtoMessage() {}

func (x *UnregisterBackendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_envoy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterBackendRequest.ProtoReflect.Descriptor instead.
func (*UnregisterBackendRequest) Descriptor() ([]byte, []int) {
	return file_proto_envoy_proto_rawDescGZIP(), []int{3}
}

func (x *UnregisterBackendRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *UnregisterBackendRequest) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

// 注销后端服务响应
type UnregisterBackendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterBackendResponse) Reset() {
	*x = UnregisterBackendResponse{}
	mi := &file_proto_envoy_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterBackendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterBackendResponse) ProtoMessage() {}

func (x *UnregisterBackendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_envoy_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterBackendResponse.ProtoReflect.Descriptor instead.
func (*UnregisterBackendResponse) Descriptor() ([]byte, []int) {
	return file_proto_envoy_proto_rawDescGZIP(), []int{4}
}

func (x *UnregisterBackendResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UnregisterBackendResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 获取后端健康状态请求
type GetBackendHealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBackendHealthRequest) Reset() {
	*x = GetBackendHealthRequest{}
	mi := &file_proto_envoy_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBackendHealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBackendHealthRequest) ProtoMessage() {}

func (x *GetBackendHealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_envoy_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBackendHealthRequest.ProtoReflect.Descriptor instead.
func (*GetBackendHealthRequest) Descriptor() ([]byte, []int) {
	return file_proto_envoy_proto_rawDescGZIP(), []int{5}
}

func (x *GetBackendHealthRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

// 后端实例状态
type BackendInstanceStatus struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Endpoint            string                 `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Healthy             bool                   `protobuf:"varint,2,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Status              string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"` // healthy, unhealthy, draining
	Weight              int32                  `protobuf:"varint,4,opt,name=weight,proto3" json:"weight,omitempty"`
	LastCheck           *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=last_check,json=lastCheck,proto3" json:"last_check,omitempty"`
	ConsecutiveFailures int32                  `protobuf:"varint,6,opt,name=consecutive_failures,json=consecutiveFailures,proto3" json:"consecutive_failures,omitempty"`
	ResponseTimeMs      float64                `protobuf:"fixed64,7,opt,name=response_time_ms,json=responseTimeMs,proto3" json:"response_time_ms,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *BackendInstanceStatus) Reset() {
	*x = BackendInstanceStatus{}
	mi := &file_proto_envoy_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackendInstanceStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackendInstanceStatus) ProtoMessage() {}

func (x *BackendInstanceStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_envoy_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackendInstanceStatus.ProtoReflect.Descriptor instead.
func (*BackendInstanceStatus) Descriptor() ([]byte, []int) {
	return file_proto_envoy_proto_rawDescGZIP(), []int{6}
}

func (x *BackendInstanceStatus) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *BackendInstanceStatus) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *BackendInstanceStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *BackendInstanceStatus) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *BackendInstanceStatus) GetLastCheck() *timestamppb.Timestamp {
	if x != nil {
		return x.LastCheck
	}
	return nil
}

func (x *BackendInstanceStatus) GetConsecutiveFailures() int32 {
	if x != nil {
		return x.ConsecutiveFailures
	}
	return 0
}

func (x *BackendInstanceStatus) GetResponseTimeMs() float64 {
	if x != nil {
		return x.ResponseTimeMs
	}
	return 0
}

// 获取后端健康状态响应
type GetBackendHealthResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Success       bool                     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Backends      []*BackendInstanceStatus `protobuf:"bytes,3,rep,name=backends,proto3" json:"backends,omitempty"`
	HealthyCount  int32                    `protobuf:"varint,4,opt,name=healthy_count,json=healthyCount,proto3" json:"healthy_count,omitempty"`
	TotalCount    int32                    `protobuf:"varint,5,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBackendHealthResponse) Reset() {
	*x = GetBackendHealthResponse{}
	mi := &file_proto_envoy_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBackendHealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBackendHealthResponse) ProtoMessage() {}

func (x *GetBackendHealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_envoy_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBackendHealthResponse.ProtoReflect.Descriptor instead.
func (*GetBackendHealthResponse) Descriptor() ([]byte, []int) {
	return file_proto_envoy_proto_rawDescGZIP(), []int{7}
}

func (x *GetBackendHealthResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetBackendHealthResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetBackendHealthResponse) GetBackends() []*BackendInstanceStatus {
	if x != nil {
		return x.Backends
	}
	return nil
}

func (x *GetBackendHealthResponse) GetHealthyCount() int32 {
	if x != nil {
		return x.HealthyCount
	}
	return 0
}

func (x *GetBackendHealthResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// 更新TLS证书请求
type UpdateTLSCertificateRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ServiceName      string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	CertificateChain string                 `protobuf:"bytes,2,opt,name=certificate_chain,json=certificateChain,proto3" json:"certificate_chain,omitempty"` // PEM格式证书链
	PrivateKey       string                 `protobuf:"bytes,3,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`                   // PEM格式私钥
	SanDomains       []string               `protobuf:"bytes,4,rep,name=san_domains,json=sanDomains,proto3" json:"san_domains,omitempty"`                   // Subject Alternative Names
	ExpiresAt        *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	AutoReload       bool                   `protobuf:"varint,6,opt,name=auto_reload,json=autoReload,proto3" json:"auto_reload,omitempty"` // 是否自动重载
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpdateTLSCertificateRequest) Reset() {
	*x = UpdateTLSCertificateRequest{}
	mi := &file_proto_envoy_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTLSCertificateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTLSCertificateRequest) ProtoMessage() {}

func (x *UpdateTLSCertificateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_envoy_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTLSCertificateRequest.ProtoReflect.Descriptor instead.
func (*UpdateTLSCertificateRequest) Descriptor() ([]byte, []int) {
	return file_proto_envoy_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateTLSCertificateRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *UpdateTLSCertificateRequest) GetCertificateChain() string {
	if x != nil {
		return x.CertificateChain
	}
	return ""
}

func (x *UpdateTLSCertificateRequest) GetPrivateKey() string {
	if x != nil {
		return x.PrivateKey
	}
	return ""
}

func (x *UpdateTLSCertificateRequest) GetSanDomains() []string {
	if x != nil {
		return x.SanDomains
	}
	return nil
}

func (x *UpdateTLSCertificateRequest) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *UpdateTLSCertificateRequest) GetAutoReload() bool {
	if x != nil {
		return x.AutoReload
	}
	return false
}

// 更新TLS证书响应
type UpdateTLSCertificateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	CertificateId string                 `protobuf:"bytes,3,opt,name=certificate_id,json=certificateId,proto3" json:"certificate_id,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTLSCertificateResponse) Reset() {
	*x = UpdateTLSCertificateResponse{}
	mi := &file_proto_envoy_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTLSCertificateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTLSCertificateResponse) ProtoMessage() {}

func (x *UpdateTLSCertificateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_envoy_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTLSCertificateResponse.ProtoReflect.Descriptor instead.
func (*UpdateTLSCertificateResponse) Descriptor() ([]byte, []int) {
	return file_proto_envoy_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateTLSCertificateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateTLSCertificateResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdateTLSCertificateResponse) GetCertificateId() string {
	if x != nil {
		return x.CertificateId
	}
	return ""
}

func (x *UpdateTLSCertificateResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// 获取TLS状态请求
type GetTLSStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTLSStatusRequest) Reset() {
	*x = GetTLSStatusRequest{}
	mi := &file_proto_envoy_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTLSStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTLSStatusRequest) ProtoMessage() {}

func (x *GetTLSStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_envoy_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTLSStatusRequest.ProtoReflect.Descriptor instead.
func (*GetTLSStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_envoy_proto_rawDescGZIP(), []int{10}
}

func (x *GetTLSStatusRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

// TLS证书状态
type TLSCertificateStatus struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CertificateId   string                 `protobuf:"bytes,1,opt,name=certificate_id,json=certificateId,proto3" json:"certificate_id,omitempty"`
	ServiceName     string                 `protobuf:"bytes,2,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Domains         []string               `protobuf:"bytes,3,rep,name=domains,proto3" json:"domains,omitempty"`
	IssuedAt        *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=issued_at,json=issuedAt,proto3" json:"issued_at,omitempty"`
	ExpiresAt       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Valid           bool                   `protobuf:"varint,6,opt,name=valid,proto3" json:"valid,omitempty"`
	Issuer          string                 `protobuf:"bytes,7,opt,name=issuer,proto3" json:"issuer,omitempty"`
	Fingerprint     string                 `protobuf:"bytes,8,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	DaysUntilExpiry int32                  `protobuf:"varint,9,opt,name=days_until_expiry,json=daysUntilExpiry,proto3" json:"days_until_expiry,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TLSCertificateStatus) Reset() {
	*x = TLSCertificateStatus{}
	mi := &file_proto_envoy_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TLSCertificateStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TLSCertificateStatus) ProtoMessage() {}

func (x *TLSCertificateStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_envoy_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TLSCertificateStatus.ProtoReflect.Descriptor instead.
func (*TLSCertificateStatus) Descriptor() ([]byte, []int) {
	return file_proto_envoy_proto_rawDescGZIP(), []int{11}
}

func (x *TLSCertificateStatus) GetCertificateId() string {
	if x != nil {
		return x.CertificateId
	}
	return ""
}

func (x *TLSCertificateStatus) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *TLSCertificateStatus) GetDomains() []string {
	if x != nil {
		return x.Domains
	}
	return nil
}

func (x *TLSCertificateStatus) GetIssuedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.IssuedAt
	}
	return nil
}

func (x *TLSCertificateStatus) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *TLSCertificateStatus) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *TLSCertificateStatus) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

func (x *TLSCertificateStatus) GetFingerprint() string {
	if x != nil {
		return x.Fingerprint
	}
	return ""
}

func (x *TLSCertificateStatus) GetDaysUntilExpiry() int32 {
	if x != nil {
		return x.DaysUntilExpiry
	}
	return 0
}

// 获取TLS状态响应
type GetTLSStatusResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Success       bool                    `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                  `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Certificates  []*TLSCertificateStatus `protobuf:"bytes,3,rep,name=certificates,proto3" json:"certificates,omitempty"`
	TlsEnabled    bool                    `protobuf:"varint,4,opt,name=tls_enabled,json=tlsEnabled,proto3" json:"tls_enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTLSStatusResponse) Reset() {
	*x = GetTLSStatusResponse{}
	mi := &file_proto_envoy_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTLSStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTLSStatusResponse) ProtoMessage() {}

func (x *GetTLSStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_envoy_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTLSStatusResponse.ProtoReflect.Descriptor instead.
func (*GetTLSStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_envoy_proto_rawDescGZIP(), []int{12}
}

func (x *GetTLSStatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetTLSStatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetTLSStatusResponse) GetCertificates() []*TLSCertificateStatus {
	if x != nil {
		return x.Certificates
	}
	return nil
}

func (x *GetTLSStatusResponse) GetTlsEnabled() bool {
	if x != nil {
		return x.TlsEnabled
	}
	return false
}

// 更新负载均衡配置请求
type UpdateLoadBalancerConfigRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ServiceName    string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Policy         LoadBalancerPolicy     `protobuf:"varint,2,opt,name=policy,proto3,enum=envoy.LoadBalancerPolicy" json:"policy,omitempty"`
	CircuitBreaker *CircuitBreakerConfig  `protobuf:"bytes,3,opt,name=circuit_breaker,json=circuitBreaker,proto3" json:"circuit_breaker,omitempty"`
	RetryConfig    *RetryConfig           `protobuf:"bytes,4,opt,name=retry_config,json=retryConfig,proto3" json:"retry_config,omitempty"`
	TimeoutConfig  *TimeoutConfig         `protobuf:"bytes,5,opt,name=timeout_config,json=timeoutConfig,proto3" json:"timeout_config,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateLoadBalancerConfigRequest) Reset() {
	*x = UpdateLoadBalancerConfigRequest{}
	mi := &file_proto_envoy_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLoadBalancerConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLoadBalancerConfigRequest) ProtoMessage() {}

func (x *UpdateLoadBalancerConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_envoy_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLoadBalancerConfigRequest.ProtoReflect.Descriptor instead.
func (*UpdateLoadBalancerConfigRequest) Descriptor() ([]byte, []int) {
	return file_proto_envoy_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateLoadBalancerConfigRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *UpdateLoadBalancerConfigRequest) GetPolicy() LoadBalancerPolicy {
	if x != nil {
		return x.Policy
	}
	return LoadBalancerPolicy_ROUND_ROBIN
}

func (x *UpdateLoadBalancerConfigRequest) GetCircuitBreaker() *CircuitBreakerConfig {
	if x != nil {
		return x.CircuitBreaker
	}
	return nil
}

func (x *UpdateLoadBalancerConfigRequest) GetRetryConfig() *RetryConfig {
	if x != nil {
		return x.RetryConfig
	}
	return nil
}

func (x *UpdateLoadBalancerConfigRequest) GetTimeoutConfig() *TimeoutConfig {
	if x != nil {
		return x.TimeoutConfig
	}
	return nil
}

// 熔断器配置
type CircuitBreakerConfig struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	MaxConnections          int32                  `protobuf:"varint,1,opt,name=max_connections,json=maxConnections,proto3" json:"max_connections,omitempty"`
	MaxPendingRequests      int32                  `protobuf:"varint,2,opt,name=max_pending_requests,json=maxPendingRequests,proto3" json:"max_pending_requests,omitempty"`
	MaxRequests             int32                  `protobuf:"varint,3,opt,name=max_requests,json=maxRequests,proto3" json:"max_requests,omitempty"`
	MaxRetries              int32                  `protobuf:"varint,4,opt,name=max_retries,json=maxRetries,proto3" json:"max_retries,omitempty"`
	Consecutive_5Xx         int32                  `protobuf:"varint,5,opt,name=consecutive_5xx,json=consecutive5xx,proto3" json:"consecutive_5xx,omitempty"`
	IntervalSeconds         int32                  `protobuf:"varint,6,opt,name=interval_seconds,json=intervalSeconds,proto3" json:"interval_seconds,omitempty"`
	BaseEjectionTimeSeconds int32                  `protobuf:"varint,7,opt,name=base_ejection_time_seconds,json=baseEjectionTimeSeconds,proto3" json:"base_ejection_time_seconds,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *CircuitBreakerConfig) Reset() {
	*x = CircuitBreakerConfig{}
	mi := &file_proto_envoy_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CircuitBreakerConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CircuitBreakerConfig) ProtoMessage() {}

func (x *CircuitBreakerConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_envoy_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CircuitBreakerConfig.ProtoReflect.Descriptor instead.
func (*CircuitBreakerConfig) Descriptor() ([]byte, []int) {
	return file_proto_envoy_proto_rawDescGZIP(), []int{14}
}

func (x *CircuitBreakerConfig) GetMaxConnections() int32 {
	if x != nil {
		return x.MaxConnections
	}
	return 0
}

func (x *CircuitBreakerConfig) GetMaxPendingRequests() int32 {
	if x != nil {
		return x.MaxPendingRequests
	}
	return 0
}

func (x *CircuitBreakerConfig) GetMaxRequests() int32 {
	if x != nil {
		return x.MaxRequests
	}
	return 0
}

func (x *CircuitBreakerConfig) GetMaxRetries() int32 {
	if x != nil {
		return x.MaxRetries
	}
	return 0
}

func (x *CircuitBreakerConfig) GetConsecutive_5Xx() int32 {
	if x != nil {
		return x.Consecutive_5Xx
	}
	return 0
}

func (x *CircuitBreakerConfig) GetIntervalSeconds() int32 {
	if x != nil {
		return x.IntervalSeconds
	}
	return 0
}

func (x *CircuitBreakerConfig) GetBaseEjectionTimeSeconds() int32 {
	if x != nil {
		return x.BaseEjectionTimeSeconds
	}
	return 0
}

// 重试配置
type RetryConfig struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	NumRetries                 int32                  `protobuf:"varint,1,opt,name=num_retries,json=numRetries,proto3" json:"num_retries,omitempty"`
	RetryOn                    []string               `protobuf:"bytes,2,rep,name=retry_on,json=retryOn,proto3" json:"retry_on,omitempty"` // 5xx, gateway-error, connect-failure, etc.
	PerTryTimeoutSeconds       int32                  `protobuf:"varint,3,opt,name=per_try_timeout_seconds,json=perTryTimeoutSeconds,proto3" json:"per_try_timeout_seconds,omitempty"`
	BackoffBaseIntervalSeconds float64                `protobuf:"fixed64,4,opt,name=backoff_base_interval_seconds,json=backoffBaseIntervalSeconds,proto3" json:"backoff_base_interval_seconds,omitempty"`
	BackoffMaxIntervalSeconds  float64                `protobuf:"fixed64,5,opt,name=backoff_max_interval_seconds,json=backoffMaxIntervalSeconds,proto3" json:"backoff_max_interval_seconds,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *RetryConfig) Reset() {
	*x = RetryConfig{}
	mi := &file_proto_envoy_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryConfig) ProtoMessage() {}

func (x *RetryConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_envoy_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryConfig.ProtoReflect.Descriptor instead.
func (*RetryConfig) Descriptor() ([]byte, []int) {
	return file_proto_envoy_proto_rawDescGZIP(), []int{15}
}

func (x *RetryConfig) GetNumRetries() int32 {
	if x != nil {
		return x.NumRetries
	}
	return 0
}

func (x *RetryConfig) GetRetryOn() []string {
	if x != nil {
		return x.RetryOn
	}
	return nil
}

func (x *RetryConfig) GetPerTryTimeoutSeconds() int32 {
	if x != nil {
		return x.PerTryTimeoutSeconds
	}
	return 0
}

func (x *RetryConfig) GetBackoffBaseIntervalSeconds() float64 {
	if x != nil {
		return x.BackoffBaseIntervalSeconds
	}
	return 0
}

func (x *RetryConfig) GetBackoffMaxIntervalSeconds() float64 {
	if x != nil {
		return x.BackoffMaxIntervalSeconds
	}
	return 0
}

// 超时配置
type TimeoutConfig struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	RequestTimeoutSeconds int32                  `protobuf:"varint,1,opt,name=request_timeout_seconds,json=requestTimeoutSeconds,proto3" json:"request_timeout_seconds,omitempty"`
	IdleTimeoutSeconds    int32                  `protobuf:"varint,2,opt,name=idle_timeout_seconds,json=idleTimeoutSeconds,proto3" json:"idle_timeout_seconds,omitempty"`
	ConnectTimeoutSeconds int32                  `protobuf:"varint,3,opt,name=connect_timeout_seconds,json=connectTimeoutSeconds,proto3" json:"connect_timeout_seconds,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *TimeoutConfig) Reset() {
	*x = TimeoutConfig{}
	mi := &file_proto_envoy_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeoutConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeoutConfig) ProtoMessage() {}

func (x *TimeoutConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_envoy_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeoutConfig.ProtoReflect.Descriptor instead.
func (*TimeoutConfig) Descriptor() ([]byte, []int) {
	return file_proto_envoy_proto_rawDescGZIP(), []int{16}
}

func (x *TimeoutConfig) GetRequestTimeoutSeconds() int32 {
	if x != nil {
		return x.RequestTimeoutSeconds
	}
	return 0
}

func (x *TimeoutConfig) GetIdleTimeoutSeconds() int32 {
	if x != nil {
		return x.IdleTimeoutSeconds
	}
	return 0
}

func (x *TimeoutConfig) GetConnectTimeoutSeconds() int32 {
	if x != nil {
		return x.ConnectTimeoutSeconds
	}
	return 0
}

// 更新负载均衡配置响应
type UpdateLoadBalancerConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateLoadBalancerConfigResponse) Reset() {
	*x = UpdateLoadBalancerConfigResponse{}
	mi := &file_proto_envoy_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLoadBalancerConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLoadBalancerConfigResponse) ProtoMessage() {}

func (x *UpdateLoadBalancerConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_envoy_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLoadBalancerConfigResponse.ProtoReflect.Descriptor instead.
func (*UpdateLoadBalancerConfigResponse) Descriptor() ([]byte, []int) {
	return file_proto_envoy_proto_rawDescGZIP(), []int{17}
}

func (x *UpdateLoadBalancerConfigResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateLoadBalancerConfigResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdateLoadBalancerConfigResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// 获取负载均衡统计请求
type GetLoadBalancerStatsRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ServiceName     string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	DurationMinutes int32                  `protobuf:"varint,2,opt,name=duration_minutes,json=durationMinutes,proto3" json:"duration_minutes,omitempty"` // 统计时间范围
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetLoadBalancerStatsRequest) Reset() {
	*x = GetLoadBalancerStatsRequest{}
	mi := &file_proto_envoy_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLoadBalancerStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLoadBalancerStatsRequest) ProtoMessage() {}

func (x *GetLoadBalancerStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_envoy_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLoadBalancerStatsRequest.ProtoReflect.Descriptor instead.
func (*GetLoadBalancerStatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_envoy_proto_rawDescGZIP(), []int{18}
}

func (x *GetLoadBalancerStatsRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *GetLoadBalancerStatsRequest) GetDurationMinutes() int32 {
	if x != nil {
		return x.DurationMinutes
	}
	return 0
}

// 负载均衡统计
type LoadBalancerStats struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	ServiceName          string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	TotalRequests        int64                  `protobuf:"varint,2,opt,name=total_requests,json=totalRequests,proto3" json:"total_requests,omitempty"`
	SuccessfulRequests   int64                  `protobuf:"varint,3,opt,name=successful_requests,json=successfulRequests,proto3" json:"successful_requests,omitempty"`
	FailedRequests       int64                  `protobuf:"varint,4,opt,name=failed_requests,json=failedRequests,proto3" json:"failed_requests,omitempty"`
	AvgResponseTimeMs    float64                `protobuf:"fixed64,5,opt,name=avg_response_time_ms,json=avgResponseTimeMs,proto3" json:"avg_response_time_ms,omitempty"`
	P95ResponseTimeMs    float64                `protobuf:"fixed64,6,opt,name=p95_response_time_ms,json=p95ResponseTimeMs,proto3" json:"p95_response_time_ms,omitempty"`
	P99ResponseTimeMs    float64                `protobuf:"fixed64,7,opt,name=p99_response_time_ms,json=p99ResponseTimeMs,proto3" json:"p99_response_time_ms,omitempty"`
	ActiveConnections    int32                  `protobuf:"varint,8,opt,name=active_connections,json=activeConnections,proto3" json:"active_connections,omitempty"`
	BackendRequestCounts map[string]int64       `protobuf:"bytes,9,rep,name=backend_request_counts,json=backendRequestCounts,proto3" json:"backend_request_counts,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	BackendResponseTimes map[string]float64     `protobuf:"bytes,10,rep,name=backend_response_times,json=backendResponseTimes,proto3" json:"backend_response_times,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	StatsPeriodStart     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=stats_period_start,json=statsPeriodStart,proto3" json:"stats_period_start,omitempty"`
	StatsPeriodEnd       *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=stats_period_end,json=statsPeriodEnd,proto3" json:"stats_period_end,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *LoadBalancerStats) Reset() {
	*x = LoadBalancerStats{}
	mi := &file_proto_envoy_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadBalancerStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadBalancerStats) ProtoMessage() {}

func (x *LoadBalancerStats) ProtoReflect() protoreflect.Message {
	mi := &file_proto_envoy_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadBalancerStats.ProtoReflect.Descriptor instead.
func (*LoadBalancerStats) Descriptor() ([]byte, []int) {
	return file_proto_envoy_proto_rawDescGZIP(), []int{19}
}

func (x *LoadBalancerStats) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *LoadBalancerStats) GetTotalRequests() int64 {
	if x != nil {
		return x.TotalRequests
	}
	return 0
}

func (x *LoadBalancerStats) GetSuccessfulRequests() int64 {
	if x != nil {
		return x.SuccessfulRequests
	}
	return 0
}

func (x *LoadBalancerStats) GetFailedRequests() int64 {
	if x != nil {
		return x.FailedRequests
	}
	return 0
}

func (x *LoadBalancerStats) GetAvgResponseTimeMs() float64 {
	if x != nil {
		return x.AvgResponseTimeMs
	}
	return 0
}

func (x *LoadBalancerStats) GetP95ResponseTimeMs() float64 {
	if x != nil {
		return x.P95ResponseTimeMs
	}
	return 0
}

func (x *LoadBalancerStats) GetP99ResponseTimeMs() float64 {
	if x != nil {
		return x.P99ResponseTimeMs
	}
	return 0
}

func (x *LoadBalancerStats) GetActiveConnections() int32 {
	if x != nil {
		return x.ActiveConnections
	}
	return 0
}

func (x *LoadBalancerStats) GetBackendRequestCounts() map[string]int64 {
	if x != nil {
		return x.BackendRequestCounts
	}
	return nil
}

func (x *LoadBalancerStats) GetBackendResponseTimes() map[string]float64 {
	if x != nil {
		return x.BackendResponseTimes
	}
	return nil
}

func (x *LoadBalancerStats) GetStatsPeriodStart() *timestamppb.Timestamp {
	if x != nil {
		return x.StatsPeriodStart
	}
	return nil
}

func (x *LoadBalancerStats) GetStatsPeriodEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.StatsPeriodEnd
	}
	return nil
}

// 获取负载均衡统计响应
type GetLoadBalancerStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Stats         *LoadBalancerStats     `protobuf:"bytes,3,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLoadBalancerStatsResponse) Reset() {
	*x = GetLoadBalancerStatsResponse{}
	mi := &file_proto_envoy_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLoadBalancerStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLoadBalancerStatsResponse) ProtoMessage() {}

func (x *GetLoadBalancerStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_envoy_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLoadBalancerStatsResponse.ProtoReflect.Descriptor instead.
func (*GetLoadBalancerStatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_envoy_proto_rawDescGZIP(), []int{20}
}

func (x *GetLoadBalancerStatsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetLoadBalancerStatsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetLoadBalancerStatsResponse) GetStats() *LoadBalancerStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

// 更新路由配置请求
type UpdateRouteConfigRequest struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	ServiceName   string                    `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Routes        []*RouteRule              `protobuf:"bytes,2,rep,name=routes,proto3" json:"routes,omitempty"`
	Headers       *HeaderModificationConfig `protobuf:"bytes,3,opt,name=headers,proto3" json:"headers,omitempty"`
	Cors          *CorsConfig               `protobuf:"bytes,4,opt,name=cors,proto3" json:"cors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRouteConfigRequest) Reset() {
	*x = UpdateRouteConfigRequest{}
	mi := &file_proto_envoy_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRouteConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRouteConfigRequest) ProtoMessage() {}

func (x *UpdateRouteConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_envoy_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRouteConfigRequest.ProtoReflect.Descriptor instead.
func (*UpdateRouteConfigRequest) Descriptor() ([]byte, []int) {
	return file_proto_envoy_proto_rawDescGZIP(), []int{21}
}

func (x *UpdateRouteConfigRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *UpdateRouteConfigRequest) GetRoutes() []*RouteRule {
	if x != nil {
		return x.Routes
	}
	return nil
}

func (x *UpdateRouteConfigRequest) GetHeaders() *HeaderModificationConfig {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *UpdateRouteConfigRequest) GetCors() *CorsConfig {
	if x != nil {
		return x.Cors
	}
	return nil
}

// 路由规则
type RouteRule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`                                                                                 // 路径匹配，支持前缀、精确、正则
	MatchType     string                 `protobuf:"bytes,2,opt,name=match_type,json=matchType,proto3" json:"match_type,omitempty"`                                                      // prefix, exact, regex
	TargetService string                 `protobuf:"bytes,3,opt,name=target_service,json=targetService,proto3" json:"target_service,omitempty"`                                          // 目标服务名
	Priority      int32                  `protobuf:"varint,4,opt,name=priority,proto3" json:"priority,omitempty"`                                                                        // 优先级
	Headers       map[string]string      `protobuf:"bytes,5,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 请求头匹配
	Methods       []string               `protobuf:"bytes,6,rep,name=methods,proto3" json:"methods,omitempty"`                                                                           // HTTP方法
	Timeout       *TimeoutConfig         `protobuf:"bytes,7,opt,name=timeout,proto3" json:"timeout,omitempty"`
	Retry         *RetryConfig           `protobuf:"bytes,8,opt,name=retry,proto3" json:"retry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteRule) Reset() {
	*x = RouteRule{}
	mi := &file_proto_envoy_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteRule) ProtoMessage() {}

func (x *RouteRule) ProtoReflect() protoreflect.Message {
	mi := &file_proto_envoy_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteRule.ProtoReflect.Descriptor instead.
func (*RouteRule) Descriptor() ([]byte, []int) {
	return file_proto_envoy_proto_rawDescGZIP(), []int{22}
}

func (x *RouteRule) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *RouteRule) GetMatchType() string {
	if x != nil {
		return x.MatchType
	}
	return ""
}

func (x *RouteRule) GetTargetService() string {
	if x != nil {
		return x.TargetService
	}
	return ""
}

func (x *RouteRule) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *RouteRule) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *RouteRule) GetMethods() []string {
	if x != nil {
		return x.Methods
	}
	return nil
}

func (x *RouteRule) GetTimeout() *TimeoutConfig {
	if x != nil {
		return x.Timeout
	}
	return nil
}

func (x *RouteRule) GetRetry() *RetryConfig {
	if x != nil {
		return x.Retry
	}
	return nil
}

// 请求头修改配置
type HeaderModificationConfig struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AddHeaders      map[string]string      `protobuf:"bytes,1,rep,name=add_headers,json=addHeaders,proto3" json:"add_headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`                // 添加请求头
	RemoveHeaders   []string               `protobuf:"bytes,2,rep,name=remove_headers,json=removeHeaders,proto3" json:"remove_headers,omitempty"`                                                                                 // 删除请求头
	SetHeaders      map[string]string      `protobuf:"bytes,3,rep,name=set_headers,json=setHeaders,proto3" json:"set_headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`                // 设置请求头
	ResponseHeaders map[string]string      `protobuf:"bytes,4,rep,name=response_headers,json=responseHeaders,proto3" json:"response_headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 响应头设置
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HeaderModificationConfig) Reset() {
	*x = HeaderModificationConfig{}
	mi := &file_proto_envoy_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeaderModificationConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeaderModificationConfig) ProtoMessage() {}

func (x *HeaderModificationConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_envoy_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeaderModificationConfig.ProtoReflect.Descriptor instead.
func (*HeaderModificationConfig) Descriptor() ([]byte, []int) {
	return file_proto_envoy_proto_rawDescGZIP(), []int{23}
}

func (x *HeaderModificationConfig) GetAddHeaders() map[string]string {
	if x != nil {
		return x.AddHeaders
	}
	return nil
}

func (x *HeaderModificationConfig) GetRemoveHeaders() []string {
	if x != nil {
		return x.RemoveHeaders
	}
	return nil
}

func (x *HeaderModificationConfig) GetSetHeaders() map[string]string {
	if x != nil {
		return x.SetHeaders
	}
	return nil
}

func (x *HeaderModificationConfig) GetResponseHeaders() map[string]string {
	if x != nil {
		return x.ResponseHeaders
	}
	return nil
}

// CORS配置
type CorsConfig struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AllowedOrigins   []string               `protobuf:"bytes,1,rep,name=allowed_origins,json=allowedOrigins,proto3" json:"allowed_origins,omitempty"`
	AllowedMethods   []string               `protobuf:"bytes,2,rep,name=allowed_methods,json=allowedMethods,proto3" json:"allowed_methods,omitempty"`
	AllowedHeaders   []string               `protobuf:"bytes,3,rep,name=allowed_headers,json=allowedHeaders,proto3" json:"allowed_headers,omitempty"`
	ExposedHeaders   []string               `protobuf:"bytes,4,rep,name=exposed_headers,json=exposedHeaders,proto3" json:"exposed_headers,omitempty"`
	AllowCredentials bool                   `protobuf:"varint,5,opt,name=allow_credentials,json=allowCredentials,proto3" json:"allow_credentials,omitempty"`
	MaxAgeSeconds    int32                  `protobuf:"varint,6,opt,name=max_age_seconds,json=maxAgeSeconds,proto3" json:"max_age_seconds,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CorsConfig) Reset() {
	*x = CorsConfig{}
	mi := &file_proto_envoy_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CorsConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CorsConfig) ProtoMessage() {}

func (x *CorsConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_envoy_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CorsConfig.ProtoReflect.Descriptor instead.
func (*CorsConfig) Descriptor() ([]byte, []int) {
	return file_proto_envoy_proto_rawDescGZIP(), []int{24}
}

func (x *CorsConfig) GetAllowedOrigins() []string {
	if x != nil {
		return x.AllowedOrigins
	}
	return nil
}

func (x *CorsConfig) GetAllowedMethods() []string {
	if x != nil {
		return x.AllowedMethods
	}
	return nil
}

func (x *CorsConfig) GetAllowedHeaders() []string {
	if x != nil {
		return x.AllowedHeaders
	}
	return nil
}

func (x *CorsConfig) GetExposedHeaders() []string {
	if x != nil {
		return x.ExposedHeaders
	}
	return nil
}

func (x *CorsConfig) GetAllowCredentials() bool {
	if x != nil {
		return x.AllowCredentials
	}
	return false
}

func (x *CorsConfig) GetMaxAgeSeconds() int32 {
	if x != nil {
		return x.MaxAgeSeconds
	}
	return 0
}

// 更新路由配置响应
type UpdateRouteConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ConfigVersion string                 `protobuf:"bytes,3,opt,name=config_version,json=configVersion,proto3" json:"config_version,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRouteConfigResponse) Reset() {
	*x = UpdateRouteConfigResponse{}
	mi := &file_proto_envoy_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRouteConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRouteConfigResponse) ProtoMessage() {}

func (x *UpdateRouteConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_envoy_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRouteConfigResponse.ProtoReflect.Descriptor instead.
func (*UpdateRouteConfigResponse) Descriptor() ([]byte, []int) {
	return file_proto_envoy_proto_rawDescGZIP(), []int{25}
}

func (x *UpdateRouteConfigResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateRouteConfigResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdateRouteConfigResponse) GetConfigVersion() string {
	if x != nil {
		return x.ConfigVersion
	}
	return ""
}

func (x *UpdateRouteConfigResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// 获取路由配置请求
type GetRouteConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRouteConfigRequest) Reset() {
	*x = GetRouteConfigRequest{}
	mi := &file_proto_envoy_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRouteConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRouteConfigRequest) ProtoMessage() {}

func (x *GetRouteConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_envoy_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRouteConfigRequest.ProtoReflect.Descriptor instead.
func (*GetRouteConfigRequest) Descriptor() ([]byte, []int) {
	return file_proto_envoy_proto_rawDescGZIP(), []int{26}
}

func (x *GetRouteConfigRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

// 获取路由配置响应
type GetRouteConfigResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Success       bool                      `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                    `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Routes        []*RouteRule              `protobuf:"bytes,3,rep,name=routes,proto3" json:"routes,omitempty"`
	Headers       *HeaderModificationConfig `protobuf:"bytes,4,opt,name=headers,proto3" json:"headers,omitempty"`
	Cors          *CorsConfig               `protobuf:"bytes,5,opt,name=cors,proto3" json:"cors,omitempty"`
	ConfigVersion string                    `protobuf:"bytes,6,opt,name=config_version,json=configVersion,proto3" json:"config_version,omitempty"`
	LastUpdated   *timestamppb.Timestamp    `protobuf:"bytes,7,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRouteConfigResponse) Reset() {
	*x = GetRouteConfigResponse{}
	mi := &file_proto_envoy_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRouteConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRouteConfigResponse) ProtoMessage() {}

func (x *GetRouteConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_envoy_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRouteConfigResponse.ProtoReflect.Descriptor instead.
func (*GetRouteConfigResponse) Descriptor() ([]byte, []int) {
	return file_proto_envoy_proto_rawDescGZIP(), []int{27}
}

func (x *GetRouteConfigResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetRouteConfigResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetRouteConfigResponse) GetRoutes() []*RouteRule {
	if x != nil {
		return x.Routes
	}
	return nil
}

func (x *GetRouteConfigResponse) GetHeaders() *HeaderModificationConfig {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *GetRouteConfigResponse) GetCors() *CorsConfig {
	if x != nil {
		return x.Cors
	}
	return nil
}

func (x *GetRouteConfigResponse) GetConfigVersion() string {
	if x != nil {
		return x.ConfigVersion
	}
	return ""
}

func (x *GetRouteConfigResponse) GetLastUpdated() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUpdated
	}
	return nil
}

var File_proto_envoy_proto protoreflect.FileDescriptor

const file_proto_envoy_proto_rawDesc = "" +
	"\n" +
	"\x11proto/envoy.proto\x12\x05envoy\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb2\x02\n" +
	"\x16RegisterBackendRequest\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12\x1a\n" +
	"\bendpoint\x18\x02 \x01(\tR\bendpoint\x12\x16\n" +
	"\x06weight\x18\x03 \x01(\x05R\x06weight\x12G\n" +
	"\bmetadata\x18\x04 \x03(\v2+.envoy.RegisterBackendRequest.MetadataEntryR\bmetadata\x12;\n" +
	"\fhealth_check\x18\x05 \x01(\v2\x18.envoy.HealthCheckConfigR\vhealthCheck\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd9\x01\n" +
	"\x11HealthCheckConfig\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12)\n" +
	"\x10interval_seconds\x18\x02 \x01(\x05R\x0fintervalSeconds\x12'\n" +
	"\x0ftimeout_seconds\x18\x03 \x01(\x05R\x0etimeoutSeconds\x12+\n" +
	"\x11healthy_threshold\x18\x04 \x01(\x05R\x10healthyThreshold\x12/\n" +
	"\x13unhealthy_threshold\x18\x05 \x01(\x05R\x12unhealthyThreshold\"l\n" +
	"\x17RegisterBackendResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"backend_id\x18\x03 \x01(\tR\tbackendId\"Y\n" +
	"\x18UnregisterBackendRequest\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12\x1a\n" +
	"\bendpoint\x18\x02 \x01(\tR\bendpoint\"O\n" +
	"\x19UnregisterBackendResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"<\n" +
	"\x17GetBackendHealthRequest\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\"\x95\x02\n" +
	"\x15BackendInstanceStatus\x12\x1a\n" +
	"\bendpoint\x18\x01 \x01(\tR\bendpoint\x12\x18\n" +
	"\ahealthy\x18\x02 \x01(\bR\ahealthy\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x16\n" +
	"\x06weight\x18\x04 \x01(\x05R\x06weight\x129\n" +
	"\n" +
	"last_check\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tlastCheck\x121\n" +
	"\x14consecutive_failures\x18\x06 \x01(\x05R\x13consecutiveFailures\x12(\n" +
	"\x10response_time_ms\x18\a \x01(\x01R\x0eresponseTimeMs\"\xce\x01\n" +
	"\x18GetBackendHealthResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x128\n" +
	"\bbackends\x18\x03 \x03(\v2\x1c.envoy.BackendInstanceStatusR\bbackends\x12#\n" +
	"\rhealthy_count\x18\x04 \x01(\x05R\fhealthyCount\x12\x1f\n" +
	"\vtotal_count\x18\x05 \x01(\x05R\n" +
	"totalCount\"\x8b\x02\n" +
	"\x1bUpdateTLSCertificateRequest\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12+\n" +
	"\x11certificate_chain\x18\x02 \x01(\tR\x10certificateChain\x12\x1f\n" +
	"\vprivate_key\x18\x03 \x01(\tR\n" +
	"privateKey\x12\x1f\n" +
	"\vsan_domains\x18\x04 \x03(\tR\n" +
	"sanDomains\x129\n" +
	"\n" +
	"expires_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12\x1f\n" +
	"\vauto_reload\x18\x06 \x01(\bR\n" +
	"autoReload\"\xb4\x01\n" +
	"\x1cUpdateTLSCertificateResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12%\n" +
	"\x0ecertificate_id\x18\x03 \x01(\tR\rcertificateId\x129\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"8\n" +
	"\x13GetTLSStatusRequest\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\"\xea\x02\n" +
	"\x14TLSCertificateStatus\x12%\n" +
	"\x0ecertificate_id\x18\x01 \x01(\tR\rcertificateId\x12!\n" +
	"\fservice_name\x18\x02 \x01(\tR\vserviceName\x12\x18\n" +
	"\adomains\x18\x03 \x03(\tR\adomains\x127\n" +
	"\tissued_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\bissuedAt\x129\n" +
	"\n" +
	"expires_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12\x14\n" +
	"\x05valid\x18\x06 \x01(\bR\x05valid\x12\x16\n" +
	"\x06issuer\x18\a \x01(\tR\x06issuer\x12 \n" +
	"\vfingerprint\x18\b \x01(\tR\vfingerprint\x12*\n" +
	"\x11days_until_expiry\x18\t \x01(\x05R\x0fdaysUntilExpiry\"\xac\x01\n" +
	"\x14GetTLSStatusResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12?\n" +
	"\fcertificates\x18\x03 \x03(\v2\x1b.envoy.TLSCertificateStatusR\fcertificates\x12\x1f\n" +
	"\vtls_enabled\x18\x04 \x01(\bR\n" +
	"tlsEnabled\"\xb1\x02\n" +
	"\x1fUpdateLoadBalancerConfigRequest\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x121\n" +
	"\x06policy\x18\x02 \x01(\x0e2\x19.envoy.LoadBalancerPolicyR\x06policy\x12D\n" +
	"\x0fcircuit_breaker\x18\x03 \x01(\v2\x1b.envoy.CircuitBreakerConfigR\x0ecircuitBreaker\x125\n" +
	"\fretry_config\x18\x04 \x01(\v2\x12.envoy.RetryConfigR\vretryConfig\x12;\n" +
	"\x0etimeout_config\x18\x05 \x01(\v2\x14.envoy.TimeoutConfigR\rtimeoutConfig\"\xc6\x02\n" +
	"\x14CircuitBreakerConfig\x12'\n" +
	"\x0fmax_connections\x18\x01 \x01(\x05R\x0emaxConnections\x120\n" +
	"\x14max_pending_requests\x18\x02 \x01(\x05R\x12maxPendingRequests\x12!\n" +
	"\fmax_requests\x18\x03 \x01(\x05R\vmaxRequests\x12\x1f\n" +
	"\vmax_retries\x18\x04 \x01(\x05R\n" +
	"maxRetries\x12'\n" +
	"\x0fconsecutive_5xx\x18\x05 \x01(\x05R\x0econsecutive5xx\x12)\n" +
	"\x10interval_seconds\x18\x06 \x01(\x05R\x0fintervalSeconds\x12;\n" +
	"\x1abase_ejection_time_seconds\x18\a \x01(\x05R\x17baseEjectionTimeSeconds\"\x84\x02\n" +
	"\vRetryConfig\x12\x1f\n" +
	"\vnum_retries\x18\x01 \x01(\x05R\n" +
	"numRetries\x12\x19\n" +
	"\bretry_on\x18\x02 \x03(\tR\aretryOn\x125\n" +
	"\x17per_try_timeout_seconds\x18\x03 \x01(\x05R\x14perTryTimeoutSeconds\x12A\n" +
	"\x1dbackoff_base_interval_seconds\x18\x04 \x01(\x01R\x1abackoffBaseIntervalSeconds\x12?\n" +
	"\x1cbackoff_max_interval_seconds\x18\x05 \x01(\x01R\x19backoffMaxIntervalSeconds\"\xb1\x01\n" +
	"\rTimeoutConfig\x126\n" +
	"\x17request_timeout_seconds\x18\x01 \x01(\x05R\x15requestTimeoutSeconds\x120\n" +
	"\x14idle_timeout_seconds\x18\x02 \x01(\x05R\x12idleTimeoutSeconds\x126\n" +
	"\x17connect_timeout_seconds\x18\x03 \x01(\x05R\x15connectTimeoutSeconds\"\x91\x01\n" +
	" UpdateLoadBalancerConfigResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x129\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"k\n" +
	"\x1bGetLoadBalancerStatsRequest\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12)\n" +
	"\x10duration_minutes\x18\x02 \x01(\x05R\x0fdurationMinutes\"\xef\x06\n" +
	"\x11LoadBalancerStats\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12%\n" +
	"\x0etotal_requests\x18\x02 \x01(\x03R\rtotalRequests\x12/\n" +
	"\x13successful_requests\x18\x03 \x01(\x03R\x12successfulRequests\x12'\n" +
	"\x0ffailed_requests\x18\x04 \x01(\x03R\x0efailedRequests\x12/\n" +
	"\x14avg_response_time_ms\x18\x05 \x01(\x01R\x11avgResponseTimeMs\x12/\n" +
	"\x14p95_response_time_ms\x18\x06 \x01(\x01R\x11p95ResponseTimeMs\x12/\n" +
	"\x14p99_response_time_ms\x18\a \x01(\x01R\x11p99ResponseTimeMs\x12-\n" +
	"\x12active_connections\x18\b \x01(\x05R\x11activeConnections\x12h\n" +
	"\x16backend_request_counts\x18\t \x03(\v22.envoy.LoadBalancerStats.BackendRequestCountsEntryR\x14backendRequestCounts\x12h\n" +
	"\x16backend_response_times\x18\n" +
	" \x03(\v22.envoy.LoadBalancerStats.BackendResponseTimesEntryR\x14backendResponseTimes\x12H\n" +
	"\x12stats_period_start\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\x10statsPeriodStart\x12D\n" +
	"\x10stats_period_end\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\x0estatsPeriodEnd\x1aG\n" +
	"\x19BackendRequestCountsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\x1aG\n" +
	"\x19BackendResponseTimesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"\x82\x01\n" +
	"\x1cGetLoadBalancerStatsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12.\n" +
	"\x05stats\x18\x03 \x01(\v2\x18.envoy.LoadBalancerStatsR\x05stats\"\xc9\x01\n" +
	"\x18UpdateRouteConfigRequest\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12(\n" +
	"\x06routes\x18\x02 \x03(\v2\x10.envoy.RouteRuleR\x06routes\x129\n" +
	"\aheaders\x18\x03 \x01(\v2\x1f.envoy.HeaderModificationConfigR\aheaders\x12%\n" +
	"\x04cors\x18\x04 \x01(\v2\x11.envoy.CorsConfigR\x04cors\"\xea\x02\n" +
	"\tRouteRule\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1d\n" +
	"\n" +
	"match_type\x18\x02 \x01(\tR\tmatchType\x12%\n" +
	"\x0etarget_service\x18\x03 \x01(\tR\rtargetService\x12\x1a\n" +
	"\bpriority\x18\x04 \x01(\x05R\bpriority\x127\n" +
	"\aheaders\x18\x05 \x03(\v2\x1d.envoy.RouteRule.HeadersEntryR\aheaders\x12\x18\n" +
	"\amethods\x18\x06 \x03(\tR\amethods\x12.\n" +
	"\atimeout\x18\a \x01(\v2\x14.envoy.TimeoutConfigR\atimeout\x12(\n" +
	"\x05retry\x18\b \x01(\v2\x12.envoy.RetryConfigR\x05retry\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x88\x04\n" +
	"\x18HeaderModificationConfig\x12P\n" +
	"\vadd_headers\x18\x01 \x03(\v2/.envoy.HeaderModificationConfig.AddHeadersEntryR\n" +
	"addHeaders\x12%\n" +
	"\x0eremove_headers\x18\x02 \x03(\tR\rremoveHeaders\x12P\n" +
	"\vset_headers\x18\x03 \x03(\v2/.envoy.HeaderModificationConfig.SetHeadersEntryR\n" +
	"setHeaders\x12_\n" +
	"\x10response_headers\x18\x04 \x03(\v24.envoy.HeaderModificationConfig.ResponseHeadersEntryR\x0fresponseHeaders\x1a=\n" +
	"\x0fAddHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a=\n" +
	"\x0fSetHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aB\n" +
	"\x14ResponseHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x85\x02\n" +
	"\n" +
	"CorsConfig\x12'\n" +
	"\x0fallowed_origins\x18\x01 \x03(\tR\x0eallowedOrigins\x12'\n" +
	"\x0fallowed_methods\x18\x02 \x03(\tR\x0eallowedMethods\x12'\n" +
	"\x0fallowed_headers\x18\x03 \x03(\tR\x0eallowedHeaders\x12'\n" +
	"\x0fexposed_headers\x18\x04 \x03(\tR\x0eexposedHeaders\x12+\n" +
	"\x11allow_credentials\x18\x05 \x01(\bR\x10allowCredentials\x12&\n" +
	"\x0fmax_age_seconds\x18\x06 \x01(\x05R\rmaxAgeSeconds\"\xb1\x01\n" +
	"\x19UpdateRouteConfigResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12%\n" +
	"\x0econfig_version\x18\x03 \x01(\tR\rconfigVersion\x129\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\":\n" +
	"\x15GetRouteConfigRequest\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\"\xbe\x02\n" +
	"\x16GetRouteConfigResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12(\n" +
	"\x06routes\x18\x03 \x03(\v2\x10.envoy.RouteRuleR\x06routes\x129\n" +
	"\aheaders\x18\x04 \x01(\v2\x1f.envoy.HeaderModificationConfigR\aheaders\x12%\n" +
	"\x04cors\x18\x05 \x01(\v2\x11.envoy.CorsConfigR\x04cors\x12%\n" +
	"\x0econfig_version\x18\x06 \x01(\tR\rconfigVersion\x12=\n" +
	"\flast_updated\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\vlastUpdated*w\n" +
	"\x12LoadBalancerPolicy\x12\x0f\n" +
	"\vROUND_ROBIN\x10\x00\x12\x15\n" +
	"\x11LEAST_CONNECTIONS\x10\x01\x12\x18\n" +
	"\x14WEIGHTED_ROUND_ROBIN\x10\x02\x12\n" +
	"\n" +
	"\x06RANDOM\x10\x03\x12\x13\n" +
	"\x0fCONSISTENT_HASH\x10\x042\xac\x06\n" +
	"\fEnvoyService\x12P\n" +
	"\x0fRegisterBackend\x12\x1d.envoy.RegisterBackendRequest\x1a\x1e.envoy.RegisterBackendResponse\x12V\n" +
	"\x11UnregisterBackend\x12\x1f.envoy.UnregisterBackendRequest\x1a .envoy.UnregisterBackendResponse\x12S\n" +
	"\x10GetBackendHealth\x12\x1e.envoy.GetBackendHealthRequest\x1a\x1f.envoy.GetBackendHealthResponse\x12_\n" +
	"\x14UpdateTLSCertificate\x12\".envoy.UpdateTLSCertificateRequest\x1a#.envoy.UpdateTLSCertificateResponse\x12G\n" +
	"\fGetTLSStatus\x12\x1a.envoy.GetTLSStatusRequest\x1a\x1b.envoy.GetTLSStatusResponse\x12k\n" +
	"\x18UpdateLoadBalancerConfig\x12&.envoy.UpdateLoadBalancerConfigRequest\x1a'.envoy.UpdateLoadBalancerConfigResponse\x12_\n" +
	"\x14GetLoadBalancerStats\x12\".envoy.GetLoadBalancerStatsRequest\x1a#.envoy.GetLoadBalancerStatsResponse\x12V\n" +
	"\x11UpdateRouteConfig\x12\x1f.envoy.UpdateRouteConfigRequest\x1a .envoy.UpdateRouteConfigResponse\x12M\n" +
	"\x0eGetRouteConfig\x12\x1c.envoy.GetRouteConfigRequest\x1a\x1d.envoy.GetRouteConfigResponseB.Z,github.com/xbox/sing-box-manager/proto/envoyb\x06proto3"

var (
	file_proto_envoy_proto_rawDescOnce sync.Once
	file_proto_envoy_proto_rawDescData []byte
)

func file_proto_envoy_proto_rawDescGZIP() []byte {
	file_proto_envoy_proto_rawDescOnce.Do(func() {
		file_proto_envoy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_envoy_proto_rawDesc), len(file_proto_envoy_proto_rawDesc)))
	})
	return file_proto_envoy_proto_rawDescData
}

var file_proto_envoy_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_envoy_proto_msgTypes = make([]protoimpl.MessageInfo, 35)
var file_proto_envoy_proto_goTypes = []any{
	(LoadBalancerPolicy)(0),                  // 0: envoy.LoadBalancerPolicy
	(*RegisterBackendRequest)(nil),           // 1: envoy.RegisterBackendRequest
	(*HealthCheckConfig)(nil),                // 2: envoy.HealthCheckConfig
	(*RegisterBackendResponse)(nil),          // 3: envoy.RegisterBackendResponse
	(*UnregisterBackendRequest)(nil),         // 4: envoy.UnregisterBackendRequest
	(*UnregisterBackendResponse)(nil),        // 5: envoy.UnregisterBackendResponse
	(*GetBackendHealthRequest)(nil),          // 6: envoy.GetBackendHealthRequest
	(*BackendInstanceStatus)(nil),            // 7: envoy.BackendInstanceStatus
	(*GetBackendHealthResponse)(nil),         // 8: envoy.GetBackendHealthResponse
	(*UpdateTLSCertificateRequest)(nil),      // 9: envoy.UpdateTLSCertificateRequest
	(*UpdateTLSCertificateResponse)(nil),     // 10: envoy.UpdateTLSCertificateResponse
	(*GetTLSStatusRequest)(nil),              // 11: envoy.GetTLSStatusRequest
	(*TLSCertificateStatus)(nil),             // 12: envoy.TLSCertificateStatus
	(*GetTLSStatusResponse)(nil),             // 13: envoy.GetTLSStatusResponse
	(*UpdateLoadBalancerConfigRequest)(nil),  // 14: envoy.UpdateLoadBalancerConfigRequest
	(*CircuitBreakerConfig)(nil),             // 15: envoy.CircuitBreakerConfig
	(*RetryConfig)(nil),                      // 16: envoy.RetryConfig
	(*TimeoutConfig)(nil),                    // 17: envoy.TimeoutConfig
	(*UpdateLoadBalancerConfigResponse)(nil), // 18: envoy.UpdateLoadBalancerConfigResponse
	(*GetLoadBalancerStatsRequest)(nil),      // 19: envoy.GetLoadBalancerStatsRequest
	(*LoadBalancerStats)(nil),                // 20: envoy.LoadBalancerStats
	(*GetLoadBalancerStatsResponse)(nil),     // 21: envoy.GetLoadBalancerStatsResponse
	(*UpdateRouteConfigRequest)(nil),         // 22: envoy.UpdateRouteConfigRequest
	(*RouteRule)(nil),                        // 23: envoy.RouteRule
	(*HeaderModificationConfig)(nil),         // 24: envoy.HeaderModificationConfig
	(*CorsConfig)(nil),                       // 25: envoy.CorsConfig
	(*UpdateRouteConfigResponse)(nil),        // 26: envoy.UpdateRouteConfigResponse
	(*GetRouteConfigRequest)(nil),            // 27: envoy.GetRouteConfigRequest
	(*GetRouteConfigResponse)(nil),           // 28: envoy.GetRouteConfigResponse
	nil,                                      // 29: envoy.RegisterBackendRequest.MetadataEntry
	nil,                                      // 30: envoy.LoadBalancerStats.BackendRequestCountsEntry
	nil,                                      // 31: envoy.LoadBalancerStats.BackendResponseTimesEntry
	nil,                                      // 32: envoy.RouteRule.HeadersEntry
	nil,                                      // 33: envoy.HeaderModificationConfig.AddHeadersEntry
	nil,                                      // 34: envoy.HeaderModificationConfig.SetHeadersEntry
	nil,                                      // 35: envoy.HeaderModificationConfig.ResponseHeadersEntry
	(*timestamppb.Timestamp)(nil),            // 36: google.protobuf.Timestamp
}
var file_proto_envoy_proto_depIdxs = []int32{
	29, // 0: envoy.RegisterBackendRequest.metadata:type_name -> envoy.RegisterBackendRequest.MetadataEntry
	2,  // 1: envoy.RegisterBackendRequest.health_check:type_name -> envoy.HealthCheckConfig
	36, // 2: envoy.BackendInstanceStatus.last_check:type_name -> google.protobuf.Timestamp
	7,  // 3: envoy.GetBackendHealthResponse.backends:type_name -> envoy.BackendInstanceStatus
	36, // 4: envoy.UpdateTLSCertificateRequest.expires_at:type_name -> google.protobuf.Timestamp
	36, // 5: envoy.UpdateTLSCertificateResponse.updated_at:type_name -> google.protobuf.Timestamp
	36, // 6: envoy.TLSCertificateStatus.issued_at:type_name -> google.protobuf.Timestamp
	36, // 7: envoy.TLSCertificateStatus.expires_at:type_name -> google.protobuf.Timestamp
	12, // 8: envoy.GetTLSStatusResponse.certificates:type_name -> envoy.TLSCertificateStatus
	0,  // 9: envoy.UpdateLoadBalancerConfigRequest.policy:type_name -> envoy.LoadBalancerPolicy
	15, // 10: envoy.UpdateLoadBalancerConfigRequest.circuit_breaker:type_name -> envoy.CircuitBreakerConfig
	16, // 11: envoy.UpdateLoadBalancerConfigRequest.retry_config:type_name -> envoy.RetryConfig
	17, // 12: envoy.UpdateLoadBalancerConfigRequest.timeout_config:type_name -> envoy.TimeoutConfig
	36, // 13: envoy.UpdateLoadBalancerConfigResponse.updated_at:type_name -> google.protobuf.Timestamp
	30, // 14: envoy.LoadBalancerStats.backend_request_counts:type_name -> envoy.LoadBalancerStats.BackendRequestCountsEntry
	31, // 15: envoy.LoadBalancerStats.backend_response_times:type_name -> envoy.LoadBalancerStats.BackendResponseTimesEntry
	36, // 16: envoy.LoadBalancerStats.stats_period_start:type_name -> google.protobuf.Timestamp
	36, // 17: envoy.LoadBalancerStats.stats_period_end:type_name -> google.protobuf.Timestamp
	20, // 18: envoy.GetLoadBalancerStatsResponse.stats:type_name -> envoy.LoadBalancerStats
	23, // 19: envoy.UpdateRouteConfigRequest.routes:type_name -> envoy.RouteRule
	24, // 20: envoy.UpdateRouteConfigRequest.headers:type_name -> envoy.HeaderModificationConfig
	25, // 21: envoy.UpdateRouteConfigRequest.cors:type_name -> envoy.CorsConfig
	32, // 22: envoy.RouteRule.headers:type_name -> envoy.RouteRule.HeadersEntry
	17, // 23: envoy.RouteRule.timeout:type_name -> envoy.TimeoutConfig
	16, // 24: envoy.RouteRule.retry:type_name -> envoy.RetryConfig
	33, // 25: envoy.HeaderModificationConfig.add_headers:type_name -> envoy.HeaderModificationConfig.AddHeadersEntry
	34, // 26: envoy.HeaderModificationConfig.set_headers:type_name -> envoy.HeaderModificationConfig.SetHeadersEntry
	35, // 27: envoy.HeaderModificationConfig.response_headers:type_name -> envoy.HeaderModificationConfig.ResponseHeadersEntry
	36, // 28: envoy.UpdateRouteConfigResponse.updated_at:type_name -> google.protobuf.Timestamp
	23, // 29: envoy.GetRouteConfigResponse.routes:type_name -> envoy.RouteRule
	24, // 30: envoy.GetRouteConfigResponse.headers:type_name -> envoy.HeaderModificationConfig
	25, // 31: envoy.GetRouteConfigResponse.cors:type_name -> envoy.CorsConfig
	36, // 32: envoy.GetRouteConfigResponse.last_updated:type_name -> google.protobuf.Timestamp
	1,  // 33: envoy.EnvoyService.RegisterBackend:input_type -> envoy.RegisterBackendRequest
	4,  // 34: envoy.EnvoyService.UnregisterBackend:input_type -> envoy.UnregisterBackendRequest
	6,  // 35: envoy.EnvoyService.GetBackendHealth:input_type -> envoy.GetBackendHealthRequest
	9,  // 36: envoy.EnvoyService.UpdateTLSCertificate:input_type -> envoy.UpdateTLSCertificateRequest
	11, // 37: envoy.EnvoyService.GetTLSStatus:input_type -> envoy.GetTLSStatusRequest
	14, // 38: envoy.EnvoyService.UpdateLoadBalancerConfig:input_type -> envoy.UpdateLoadBalancerConfigRequest
	19, // 39: envoy.EnvoyService.GetLoadBalancerStats:input_type -> envoy.GetLoadBalancerStatsRequest
	22, // 40: envoy.EnvoyService.UpdateRouteConfig:input_type -> envoy.UpdateRouteConfigRequest
	27, // 41: envoy.EnvoyService.GetRouteConfig:input_type -> envoy.GetRouteConfigRequest
	3,  // 42: envoy.EnvoyService.RegisterBackend:output_type -> envoy.RegisterBackendResponse
	5,  // 43: envoy.EnvoyService.UnregisterBackend:output_type -> envoy.UnregisterBackendResponse
	8,  // 44: envoy.EnvoyService.GetBackendHealth:output_type -> envoy.GetBackendHealthResponse
	10, // 45: envoy.EnvoyService.UpdateTLSCertificate:output_type -> envoy.UpdateTLSCertificateResponse
	13, // 46: envoy.EnvoyService.GetTLSStatus:output_type -> envoy.GetTLSStatusResponse
	18, // 47: envoy.EnvoyService.UpdateLoadBalancerConfig:output_type -> envoy.UpdateLoadBalancerConfigResponse
	21, // 48: envoy.EnvoyService.GetLoadBalancerStats:output_type -> envoy.GetLoadBalancerStatsResponse
	26, // 49: envoy.EnvoyService.UpdateRouteConfig:output_type -> envoy.UpdateRouteConfigResponse
	28, // 50: envoy.EnvoyService.GetRouteConfig:output_type -> envoy.GetRouteConfigResponse
	42, // [42:51] is the sub-list for method output_type
	33, // [33:42] is the sub-list for method input_type
	33, // [33:33] is the sub-list for extension type_name
	33, // [33:33] is the sub-list for extension extendee
	0,  // [0:33] is the sub-list for field type_name
}

func init() { file_proto_envoy_proto_init() }
func file_proto_envoy_proto_init() {
	if File_proto_envoy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_envoy_proto_rawDesc), len(file_proto_envoy_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   35,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_envoy_proto_goTypes,
		DependencyIndexes: file_proto_envoy_proto_depIdxs,
		EnumInfos:         file_proto_envoy_proto_enumTypes,
		MessageInfos:      file_proto_envoy_proto_msgTypes,
	}.Build()
	File_proto_envoy_proto = out.File
	file_proto_envoy_proto_goTypes = nil
	file_proto_envoy_proto_depIdxs = nil
}
