# Xbox Agent 配置文件
server:
  host: "0.0.0.0"
  port: 8081
  mode: "release"

database:
  driver: "mysql"
  host: "localhost"
  port: 3306
  username: "root"
  password: "password"
  database: "xbox_manager"
  charset: "utf8mb4"
  options: "parseTime=True&loc=Local"

grpc:
  host: "0.0.0.0" 
  port: 9091
  tls:
    enabled: true                              # 启用TLS + mTLS双向认证
    cert_file: "./certs/client/client-cert.pem"  # Agent客户端证书
    key_file: "./certs/client/client-key.pem"    # Agent客户端私钥
    ca_file: "./certs/ca/ca-cert.pem"           # CA根证书（验证服务器）
    server_name: "xbox-controller"              # 服务器名称验证

log:
  level: "info"
  format: "json"
  output: "stdout"
  file: "logs/agent.log"
  max_size: 100
  max_backups: 10
  max_age: 30

agent:
  id: ""  # 空值将自动生成
  controller_addr: "localhost:9090"
  heartbeat_interval: 30
  singbox_config: "./configs/sing-box.json"
  singbox_binary: "sing-box"