// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: proto/backend.proto

package backend

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 健康检查请求
type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_proto_backend_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_backend_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_proto_backend_proto_rawDescGZIP(), []int{0}
}

// 健康检查响应
type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Service       string                 `protobuf:"bytes,3,opt,name=service,proto3" json:"service,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_proto_backend_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_backend_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_proto_backend_proto_rawDescGZIP(), []int{1}
}

func (x *HealthCheckResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *HealthCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthCheckResponse) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *HealthCheckResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// 获取Agent列表请求
type GetAgentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	StatusFilter  string                 `protobuf:"bytes,3,opt,name=status_filter,json=statusFilter,proto3" json:"status_filter,omitempty"` // online, offline, unknown
	CountryFilter string                 `protobuf:"bytes,4,opt,name=country_filter,json=countryFilter,proto3" json:"country_filter,omitempty"`
	RegionFilter  string                 `protobuf:"bytes,5,opt,name=region_filter,json=regionFilter,proto3" json:"region_filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentsRequest) Reset() {
	*x = GetAgentsRequest{}
	mi := &file_proto_backend_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentsRequest) ProtoMessage() {}

func (x *GetAgentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_backend_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentsRequest.ProtoReflect.Descriptor instead.
func (*GetAgentsRequest) Descriptor() ([]byte, []int) {
	return file_proto_backend_proto_rawDescGZIP(), []int{2}
}

func (x *GetAgentsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetAgentsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetAgentsRequest) GetStatusFilter() string {
	if x != nil {
		return x.StatusFilter
	}
	return ""
}

func (x *GetAgentsRequest) GetCountryFilter() string {
	if x != nil {
		return x.CountryFilter
	}
	return ""
}

func (x *GetAgentsRequest) GetRegionFilter() string {
	if x != nil {
		return x.RegionFilter
	}
	return ""
}

// Agent信息
type AgentInfo struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	AgentId            string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Hostname           string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	IpAddress          string                 `protobuf:"bytes,3,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	Status             string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"` // online, offline, unknown
	Country            string                 `protobuf:"bytes,5,opt,name=country,proto3" json:"country,omitempty"`
	Region             string                 `protobuf:"bytes,6,opt,name=region,proto3" json:"region,omitempty"`
	City               string                 `protobuf:"bytes,7,opt,name=city,proto3" json:"city,omitempty"`
	CurrentConnections int32                  `protobuf:"varint,8,opt,name=current_connections,json=currentConnections,proto3" json:"current_connections,omitempty"`
	CpuUsage           float64                `protobuf:"fixed64,9,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	MemoryUsage        float64                `protobuf:"fixed64,10,opt,name=memory_usage,json=memoryUsage,proto3" json:"memory_usage,omitempty"`
	DiskUsage          float64                `protobuf:"fixed64,11,opt,name=disk_usage,json=diskUsage,proto3" json:"disk_usage,omitempty"`
	NetworkLatency     int32                  `protobuf:"varint,12,opt,name=network_latency,json=networkLatency,proto3" json:"network_latency,omitempty"`
	LastHeartbeat      *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=last_heartbeat,json=lastHeartbeat,proto3" json:"last_heartbeat,omitempty"`
	RegisteredAt       *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=registered_at,json=registeredAt,proto3" json:"registered_at,omitempty"`
	Version            string                 `protobuf:"bytes,15,opt,name=version,proto3" json:"version,omitempty"`
	Metadata           map[string]string      `protobuf:"bytes,16,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	IpRangeInfo        *IPRangeInfo           `protobuf:"bytes,17,opt,name=ip_range_info,json=ipRangeInfo,proto3" json:"ip_range_info,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AgentInfo) Reset() {
	*x = AgentInfo{}
	mi := &file_proto_backend_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentInfo) ProtoMessage() {}

func (x *AgentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_backend_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentInfo.ProtoReflect.Descriptor instead.
func (*AgentInfo) Descriptor() ([]byte, []int) {
	return file_proto_backend_proto_rawDescGZIP(), []int{3}
}

func (x *AgentInfo) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentInfo) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *AgentInfo) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *AgentInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AgentInfo) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *AgentInfo) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *AgentInfo) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *AgentInfo) GetCurrentConnections() int32 {
	if x != nil {
		return x.CurrentConnections
	}
	return 0
}

func (x *AgentInfo) GetCpuUsage() float64 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *AgentInfo) GetMemoryUsage() float64 {
	if x != nil {
		return x.MemoryUsage
	}
	return 0
}

func (x *AgentInfo) GetDiskUsage() float64 {
	if x != nil {
		return x.DiskUsage
	}
	return 0
}

func (x *AgentInfo) GetNetworkLatency() int32 {
	if x != nil {
		return x.NetworkLatency
	}
	return 0
}

func (x *AgentInfo) GetLastHeartbeat() *timestamppb.Timestamp {
	if x != nil {
		return x.LastHeartbeat
	}
	return nil
}

func (x *AgentInfo) GetRegisteredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RegisteredAt
	}
	return nil
}

func (x *AgentInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *AgentInfo) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *AgentInfo) GetIpRangeInfo() *IPRangeInfo {
	if x != nil {
		return x.IpRangeInfo
	}
	return nil
}

// 获取Agent列表响应
type GetAgentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Agents        []*AgentInfo           `protobuf:"bytes,3,rep,name=agents,proto3" json:"agents,omitempty"`
	TotalCount    int32                  `protobuf:"varint,4,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Page          int32                  `protobuf:"varint,5,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,6,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentsResponse) Reset() {
	*x = GetAgentsResponse{}
	mi := &file_proto_backend_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentsResponse) ProtoMessage() {}

func (x *GetAgentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_backend_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentsResponse.ProtoReflect.Descriptor instead.
func (*GetAgentsResponse) Descriptor() ([]byte, []int) {
	return file_proto_backend_proto_rawDescGZIP(), []int{4}
}

func (x *GetAgentsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetAgentsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetAgentsResponse) GetAgents() []*AgentInfo {
	if x != nil {
		return x.Agents
	}
	return nil
}

func (x *GetAgentsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *GetAgentsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetAgentsResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// 获取单个Agent请求
type GetAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentRequest) Reset() {
	*x = GetAgentRequest{}
	mi := &file_proto_backend_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentRequest) ProtoMessage() {}

func (x *GetAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_backend_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentRequest.ProtoReflect.Descriptor instead.
func (*GetAgentRequest) Descriptor() ([]byte, []int) {
	return file_proto_backend_proto_rawDescGZIP(), []int{5}
}

func (x *GetAgentRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

// 获取单个Agent响应
type GetAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Agent         *AgentInfo             `protobuf:"bytes,3,opt,name=agent,proto3" json:"agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentResponse) Reset() {
	*x = GetAgentResponse{}
	mi := &file_proto_backend_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentResponse) ProtoMessage() {}

func (x *GetAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_backend_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentResponse.ProtoReflect.Descriptor instead.
func (*GetAgentResponse) Descriptor() ([]byte, []int) {
	return file_proto_backend_proto_rawDescGZIP(), []int{6}
}

func (x *GetAgentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetAgentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetAgentResponse) GetAgent() *AgentInfo {
	if x != nil {
		return x.Agent
	}
	return nil
}

// 获取Agent统计请求
type GetAgentStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentStatsRequest) Reset() {
	*x = GetAgentStatsRequest{}
	mi := &file_proto_backend_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentStatsRequest) ProtoMessage() {}

func (x *GetAgentStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_backend_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentStatsRequest.ProtoReflect.Descriptor instead.
func (*GetAgentStatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_backend_proto_rawDescGZIP(), []int{7}
}

// Agent统计信息
type AgentStats struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TotalAgents      int32                  `protobuf:"varint,1,opt,name=total_agents,json=totalAgents,proto3" json:"total_agents,omitempty"`
	OnlineAgents     int32                  `protobuf:"varint,2,opt,name=online_agents,json=onlineAgents,proto3" json:"online_agents,omitempty"`
	OfflineAgents    int32                  `protobuf:"varint,3,opt,name=offline_agents,json=offlineAgents,proto3" json:"offline_agents,omitempty"`
	UnknownAgents    int32                  `protobuf:"varint,4,opt,name=unknown_agents,json=unknownAgents,proto3" json:"unknown_agents,omitempty"`
	AvgCpuUsage      float64                `protobuf:"fixed64,5,opt,name=avg_cpu_usage,json=avgCpuUsage,proto3" json:"avg_cpu_usage,omitempty"`
	AvgMemoryUsage   float64                `protobuf:"fixed64,6,opt,name=avg_memory_usage,json=avgMemoryUsage,proto3" json:"avg_memory_usage,omitempty"`
	TotalConnections int32                  `protobuf:"varint,7,opt,name=total_connections,json=totalConnections,proto3" json:"total_connections,omitempty"`
	AgentsByCountry  map[string]int32       `protobuf:"bytes,8,rep,name=agents_by_country,json=agentsByCountry,proto3" json:"agents_by_country,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	AgentsByRegion   map[string]int32       `protobuf:"bytes,9,rep,name=agents_by_region,json=agentsByRegion,proto3" json:"agents_by_region,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AgentStats) Reset() {
	*x = AgentStats{}
	mi := &file_proto_backend_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentStats) ProtoMessage() {}

func (x *AgentStats) ProtoReflect() protoreflect.Message {
	mi := &file_proto_backend_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentStats.ProtoReflect.Descriptor instead.
func (*AgentStats) Descriptor() ([]byte, []int) {
	return file_proto_backend_proto_rawDescGZIP(), []int{8}
}

func (x *AgentStats) GetTotalAgents() int32 {
	if x != nil {
		return x.TotalAgents
	}
	return 0
}

func (x *AgentStats) GetOnlineAgents() int32 {
	if x != nil {
		return x.OnlineAgents
	}
	return 0
}

func (x *AgentStats) GetOfflineAgents() int32 {
	if x != nil {
		return x.OfflineAgents
	}
	return 0
}

func (x *AgentStats) GetUnknownAgents() int32 {
	if x != nil {
		return x.UnknownAgents
	}
	return 0
}

func (x *AgentStats) GetAvgCpuUsage() float64 {
	if x != nil {
		return x.AvgCpuUsage
	}
	return 0
}

func (x *AgentStats) GetAvgMemoryUsage() float64 {
	if x != nil {
		return x.AvgMemoryUsage
	}
	return 0
}

func (x *AgentStats) GetTotalConnections() int32 {
	if x != nil {
		return x.TotalConnections
	}
	return 0
}

func (x *AgentStats) GetAgentsByCountry() map[string]int32 {
	if x != nil {
		return x.AgentsByCountry
	}
	return nil
}

func (x *AgentStats) GetAgentsByRegion() map[string]int32 {
	if x != nil {
		return x.AgentsByRegion
	}
	return nil
}

// 获取Agent统计响应
type GetAgentStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Stats         *AgentStats            `protobuf:"bytes,3,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentStatsResponse) Reset() {
	*x = GetAgentStatsResponse{}
	mi := &file_proto_backend_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentStatsResponse) ProtoMessage() {}

func (x *GetAgentStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_backend_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentStatsResponse.ProtoReflect.Descriptor instead.
func (*GetAgentStatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_backend_proto_rawDescGZIP(), []int{9}
}

func (x *GetAgentStatsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetAgentStatsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetAgentStatsResponse) GetStats() *AgentStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

// 部署Agent请求
type DeployAgentRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	NodeIp            string                 `protobuf:"bytes,1,opt,name=node_ip,json=nodeIp,proto3" json:"node_ip,omitempty"`
	SshPort           int32                  `protobuf:"varint,2,opt,name=ssh_port,json=sshPort,proto3" json:"ssh_port,omitempty"`
	SshUser           string                 `protobuf:"bytes,3,opt,name=ssh_user,json=sshUser,proto3" json:"ssh_user,omitempty"`
	SshPassword       string                 `protobuf:"bytes,4,opt,name=ssh_password,json=sshPassword,proto3" json:"ssh_password,omitempty"`
	ControllerUrl     string                 `protobuf:"bytes,5,opt,name=controller_url,json=controllerUrl,proto3" json:"controller_url,omitempty"`
	DeploymentOptions map[string]string      `protobuf:"bytes,6,rep,name=deployment_options,json=deploymentOptions,proto3" json:"deployment_options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DeployAgentRequest) Reset() {
	*x = DeployAgentRequest{}
	mi := &file_proto_backend_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployAgentRequest) ProtoMessage() {}

func (x *DeployAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_backend_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployAgentRequest.ProtoReflect.Descriptor instead.
func (*DeployAgentRequest) Descriptor() ([]byte, []int) {
	return file_proto_backend_proto_rawDescGZIP(), []int{10}
}

func (x *DeployAgentRequest) GetNodeIp() string {
	if x != nil {
		return x.NodeIp
	}
	return ""
}

func (x *DeployAgentRequest) GetSshPort() int32 {
	if x != nil {
		return x.SshPort
	}
	return 0
}

func (x *DeployAgentRequest) GetSshUser() string {
	if x != nil {
		return x.SshUser
	}
	return ""
}

func (x *DeployAgentRequest) GetSshPassword() string {
	if x != nil {
		return x.SshPassword
	}
	return ""
}

func (x *DeployAgentRequest) GetControllerUrl() string {
	if x != nil {
		return x.ControllerUrl
	}
	return ""
}

func (x *DeployAgentRequest) GetDeploymentOptions() map[string]string {
	if x != nil {
		return x.DeploymentOptions
	}
	return nil
}

// 部署Agent响应
type DeployAgentResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Success               bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message               string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	AgentId               string                 `protobuf:"bytes,3,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	DeploymentLog         string                 `protobuf:"bytes,4,opt,name=deployment_log,json=deploymentLog,proto3" json:"deployment_log,omitempty"`
	DeploymentTimeSeconds int32                  `protobuf:"varint,5,opt,name=deployment_time_seconds,json=deploymentTimeSeconds,proto3" json:"deployment_time_seconds,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *DeployAgentResponse) Reset() {
	*x = DeployAgentResponse{}
	mi := &file_proto_backend_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployAgentResponse) ProtoMessage() {}

func (x *DeployAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_backend_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployAgentResponse.ProtoReflect.Descriptor instead.
func (*DeployAgentResponse) Descriptor() ([]byte, []int) {
	return file_proto_backend_proto_rawDescGZIP(), []int{11}
}

func (x *DeployAgentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeployAgentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DeployAgentResponse) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *DeployAgentResponse) GetDeploymentLog() string {
	if x != nil {
		return x.DeploymentLog
	}
	return ""
}

func (x *DeployAgentResponse) GetDeploymentTimeSeconds() int32 {
	if x != nil {
		return x.DeploymentTimeSeconds
	}
	return 0
}

// 卸载Agent请求
type UninstallAgentRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AgentId        string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	ForceUninstall bool                   `protobuf:"varint,2,opt,name=force_uninstall,json=forceUninstall,proto3" json:"force_uninstall,omitempty"`
	Reason         string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	TimeoutSeconds int32                  `protobuf:"varint,4,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UninstallAgentRequest) Reset() {
	*x = UninstallAgentRequest{}
	mi := &file_proto_backend_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UninstallAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UninstallAgentRequest) ProtoMessage() {}

func (x *UninstallAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_backend_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UninstallAgentRequest.ProtoReflect.Descriptor instead.
func (*UninstallAgentRequest) Descriptor() ([]byte, []int) {
	return file_proto_backend_proto_rawDescGZIP(), []int{12}
}

func (x *UninstallAgentRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *UninstallAgentRequest) GetForceUninstall() bool {
	if x != nil {
		return x.ForceUninstall
	}
	return false
}

func (x *UninstallAgentRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *UninstallAgentRequest) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

// 卸载Agent响应
type UninstallAgentResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Success         bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message         string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	UninstallStatus string                 `protobuf:"bytes,3,opt,name=uninstall_status,json=uninstallStatus,proto3" json:"uninstall_status,omitempty"`
	CleanedFiles    []string               `protobuf:"bytes,4,rep,name=cleaned_files,json=cleanedFiles,proto3" json:"cleaned_files,omitempty"`
	CleanupTimeMs   int64                  `protobuf:"varint,5,opt,name=cleanup_time_ms,json=cleanupTimeMs,proto3" json:"cleanup_time_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UninstallAgentResponse) Reset() {
	*x = UninstallAgentResponse{}
	mi := &file_proto_backend_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UninstallAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UninstallAgentResponse) ProtoMessage() {}

func (x *UninstallAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_backend_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UninstallAgentResponse.ProtoReflect.Descriptor instead.
func (*UninstallAgentResponse) Descriptor() ([]byte, []int) {
	return file_proto_backend_proto_rawDescGZIP(), []int{13}
}

func (x *UninstallAgentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UninstallAgentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UninstallAgentResponse) GetUninstallStatus() string {
	if x != nil {
		return x.UninstallStatus
	}
	return ""
}

func (x *UninstallAgentResponse) GetCleanedFiles() []string {
	if x != nil {
		return x.CleanedFiles
	}
	return nil
}

func (x *UninstallAgentResponse) GetCleanupTimeMs() int64 {
	if x != nil {
		return x.CleanupTimeMs
	}
	return 0
}

// 更新Agent配置请求
type UpdateAgentConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	ConfigType    string                 `protobuf:"bytes,2,opt,name=config_type,json=configType,proto3" json:"config_type,omitempty"` // singbox, system, filters, multiplex
	ConfigContent string                 `protobuf:"bytes,3,opt,name=config_content,json=configContent,proto3" json:"config_content,omitempty"`
	ForceUpdate   bool                   `protobuf:"varint,4,opt,name=force_update,json=forceUpdate,proto3" json:"force_update,omitempty"`
	ConfigVersion string                 `protobuf:"bytes,5,opt,name=config_version,json=configVersion,proto3" json:"config_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAgentConfigRequest) Reset() {
	*x = UpdateAgentConfigRequest{}
	mi := &file_proto_backend_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAgentConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAgentConfigRequest) ProtoMessage() {}

func (x *UpdateAgentConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_backend_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAgentConfigRequest.ProtoReflect.Descriptor instead.
func (*UpdateAgentConfigRequest) Descriptor() ([]byte, []int) {
	return file_proto_backend_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateAgentConfigRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *UpdateAgentConfigRequest) GetConfigType() string {
	if x != nil {
		return x.ConfigType
	}
	return ""
}

func (x *UpdateAgentConfigRequest) GetConfigContent() string {
	if x != nil {
		return x.ConfigContent
	}
	return ""
}

func (x *UpdateAgentConfigRequest) GetForceUpdate() bool {
	if x != nil {
		return x.ForceUpdate
	}
	return false
}

func (x *UpdateAgentConfigRequest) GetConfigVersion() string {
	if x != nil {
		return x.ConfigVersion
	}
	return ""
}

// 更新Agent配置响应
type UpdateAgentConfigResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Success        bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message        string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	AppliedVersion string                 `protobuf:"bytes,3,opt,name=applied_version,json=appliedVersion,proto3" json:"applied_version,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateAgentConfigResponse) Reset() {
	*x = UpdateAgentConfigResponse{}
	mi := &file_proto_backend_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAgentConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAgentConfigResponse) ProtoMessage() {}

func (x *UpdateAgentConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_backend_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAgentConfigResponse.ProtoReflect.Descriptor instead.
func (*UpdateAgentConfigResponse) Descriptor() ([]byte, []int) {
	return file_proto_backend_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateAgentConfigResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateAgentConfigResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdateAgentConfigResponse) GetAppliedVersion() string {
	if x != nil {
		return x.AppliedVersion
	}
	return ""
}

func (x *UpdateAgentConfigResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// 获取Agent监控请求
type GetAgentMonitoringRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AgentId         string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	DurationMinutes int32                  `protobuf:"varint,2,opt,name=duration_minutes,json=durationMinutes,proto3" json:"duration_minutes,omitempty"` // 监控数据时间范围（分钟）
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetAgentMonitoringRequest) Reset() {
	*x = GetAgentMonitoringRequest{}
	mi := &file_proto_backend_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentMonitoringRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentMonitoringRequest) ProtoMessage() {}

func (x *GetAgentMonitoringRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_backend_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentMonitoringRequest.ProtoReflect.Descriptor instead.
func (*GetAgentMonitoringRequest) Descriptor() ([]byte, []int) {
	return file_proto_backend_proto_rawDescGZIP(), []int{16}
}

func (x *GetAgentMonitoringRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *GetAgentMonitoringRequest) GetDurationMinutes() int32 {
	if x != nil {
		return x.DurationMinutes
	}
	return 0
}

// 监控数据点
type MonitoringDataPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Value         float64                `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MonitoringDataPoint) Reset() {
	*x = MonitoringDataPoint{}
	mi := &file_proto_backend_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonitoringDataPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonitoringDataPoint) ProtoMessage() {}

func (x *MonitoringDataPoint) ProtoReflect() protoreflect.Message {
	mi := &file_proto_backend_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonitoringDataPoint.ProtoReflect.Descriptor instead.
func (*MonitoringDataPoint) Descriptor() ([]byte, []int) {
	return file_proto_backend_proto_rawDescGZIP(), []int{17}
}

func (x *MonitoringDataPoint) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *MonitoringDataPoint) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

// Agent监控数据
type AgentMonitoringData struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	AgentId            string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	CpuUsage           []*MonitoringDataPoint `protobuf:"bytes,2,rep,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	MemoryUsage        []*MonitoringDataPoint `protobuf:"bytes,3,rep,name=memory_usage,json=memoryUsage,proto3" json:"memory_usage,omitempty"`
	DiskUsage          []*MonitoringDataPoint `protobuf:"bytes,4,rep,name=disk_usage,json=diskUsage,proto3" json:"disk_usage,omitempty"`
	NetworkConnections []*MonitoringDataPoint `protobuf:"bytes,5,rep,name=network_connections,json=networkConnections,proto3" json:"network_connections,omitempty"`
	SingboxStatus      string                 `protobuf:"bytes,6,opt,name=singbox_status,json=singboxStatus,proto3" json:"singbox_status,omitempty"`
	LastUpdate         *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=last_update,json=lastUpdate,proto3" json:"last_update,omitempty"`
	ActiveConnections  int32                  `protobuf:"varint,8,opt,name=active_connections,json=activeConnections,proto3" json:"active_connections,omitempty"`
	NetworkLatencyMs   float64                `protobuf:"fixed64,9,opt,name=network_latency_ms,json=networkLatencyMs,proto3" json:"network_latency_ms,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AgentMonitoringData) Reset() {
	*x = AgentMonitoringData{}
	mi := &file_proto_backend_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMonitoringData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMonitoringData) ProtoMessage() {}

func (x *AgentMonitoringData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_backend_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMonitoringData.ProtoReflect.Descriptor instead.
func (*AgentMonitoringData) Descriptor() ([]byte, []int) {
	return file_proto_backend_proto_rawDescGZIP(), []int{18}
}

func (x *AgentMonitoringData) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentMonitoringData) GetCpuUsage() []*MonitoringDataPoint {
	if x != nil {
		return x.CpuUsage
	}
	return nil
}

func (x *AgentMonitoringData) GetMemoryUsage() []*MonitoringDataPoint {
	if x != nil {
		return x.MemoryUsage
	}
	return nil
}

func (x *AgentMonitoringData) GetDiskUsage() []*MonitoringDataPoint {
	if x != nil {
		return x.DiskUsage
	}
	return nil
}

func (x *AgentMonitoringData) GetNetworkConnections() []*MonitoringDataPoint {
	if x != nil {
		return x.NetworkConnections
	}
	return nil
}

func (x *AgentMonitoringData) GetSingboxStatus() string {
	if x != nil {
		return x.SingboxStatus
	}
	return ""
}

func (x *AgentMonitoringData) GetLastUpdate() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUpdate
	}
	return nil
}

func (x *AgentMonitoringData) GetActiveConnections() int32 {
	if x != nil {
		return x.ActiveConnections
	}
	return 0
}

func (x *AgentMonitoringData) GetNetworkLatencyMs() float64 {
	if x != nil {
		return x.NetworkLatencyMs
	}
	return 0
}

// 获取Agent监控响应
type GetAgentMonitoringResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Success        bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message        string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	MonitoringData *AgentMonitoringData   `protobuf:"bytes,3,opt,name=monitoring_data,json=monitoringData,proto3" json:"monitoring_data,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetAgentMonitoringResponse) Reset() {
	*x = GetAgentMonitoringResponse{}
	mi := &file_proto_backend_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentMonitoringResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentMonitoringResponse) ProtoMessage() {}

func (x *GetAgentMonitoringResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_backend_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentMonitoringResponse.ProtoReflect.Descriptor instead.
func (*GetAgentMonitoringResponse) Descriptor() ([]byte, []int) {
	return file_proto_backend_proto_rawDescGZIP(), []int{19}
}

func (x *GetAgentMonitoringResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetAgentMonitoringResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetAgentMonitoringResponse) GetMonitoringData() *AgentMonitoringData {
	if x != nil {
		return x.MonitoringData
	}
	return nil
}

// 获取IP段请求
type GetIPRangesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CountryFilter string                 `protobuf:"bytes,1,opt,name=country_filter,json=countryFilter,proto3" json:"country_filter,omitempty"`
	RegionFilter  string                 `protobuf:"bytes,2,opt,name=region_filter,json=regionFilter,proto3" json:"region_filter,omitempty"`
	IspFilter     string                 `protobuf:"bytes,3,opt,name=isp_filter,json=ispFilter,proto3" json:"isp_filter,omitempty"`
	IncludeAgents bool                   `protobuf:"varint,4,opt,name=include_agents,json=includeAgents,proto3" json:"include_agents,omitempty"` // 是否包含Agent详细信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIPRangesRequest) Reset() {
	*x = GetIPRangesRequest{}
	mi := &file_proto_backend_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIPRangesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIPRangesRequest) ProtoMessage() {}

func (x *GetIPRangesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_backend_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIPRangesRequest.ProtoReflect.Descriptor instead.
func (*GetIPRangesRequest) Descriptor() ([]byte, []int) {
	return file_proto_backend_proto_rawDescGZIP(), []int{20}
}

func (x *GetIPRangesRequest) GetCountryFilter() string {
	if x != nil {
		return x.CountryFilter
	}
	return ""
}

func (x *GetIPRangesRequest) GetRegionFilter() string {
	if x != nil {
		return x.RegionFilter
	}
	return ""
}

func (x *GetIPRangesRequest) GetIspFilter() string {
	if x != nil {
		return x.IspFilter
	}
	return ""
}

func (x *GetIPRangesRequest) GetIncludeAgents() bool {
	if x != nil {
		return x.IncludeAgents
	}
	return false
}

// IP段信息
type IPRangeInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	IpRange         string                 `protobuf:"bytes,1,opt,name=ip_range,json=ipRange,proto3" json:"ip_range,omitempty"` // IP段，如 192.168.1.0/24
	Country         string                 `protobuf:"bytes,2,opt,name=country,proto3" json:"country,omitempty"`
	Region          string                 `protobuf:"bytes,3,opt,name=region,proto3" json:"region,omitempty"`
	City            string                 `protobuf:"bytes,4,opt,name=city,proto3" json:"city,omitempty"`
	Isp             string                 `protobuf:"bytes,5,opt,name=isp,proto3" json:"isp,omitempty"`
	AgentCount      int32                  `protobuf:"varint,6,opt,name=agent_count,json=agentCount,proto3" json:"agent_count,omitempty"`               // 该IP段下的Agent数量
	Agents          []*AgentInfo           `protobuf:"bytes,7,rep,name=agents,proto3" json:"agents,omitempty"`                                          // Agent详细信息（可选）
	DetectionMethod string                 `protobuf:"bytes,8,opt,name=detection_method,json=detectionMethod,proto3" json:"detection_method,omitempty"` // auto, manual, api
	DetectedAt      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=detected_at,json=detectedAt,proto3" json:"detected_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *IPRangeInfo) Reset() {
	*x = IPRangeInfo{}
	mi := &file_proto_backend_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IPRangeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IPRangeInfo) ProtoMessage() {}

func (x *IPRangeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_backend_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IPRangeInfo.ProtoReflect.Descriptor instead.
func (*IPRangeInfo) Descriptor() ([]byte, []int) {
	return file_proto_backend_proto_rawDescGZIP(), []int{21}
}

func (x *IPRangeInfo) GetIpRange() string {
	if x != nil {
		return x.IpRange
	}
	return ""
}

func (x *IPRangeInfo) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *IPRangeInfo) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *IPRangeInfo) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *IPRangeInfo) GetIsp() string {
	if x != nil {
		return x.Isp
	}
	return ""
}

func (x *IPRangeInfo) GetAgentCount() int32 {
	if x != nil {
		return x.AgentCount
	}
	return 0
}

func (x *IPRangeInfo) GetAgents() []*AgentInfo {
	if x != nil {
		return x.Agents
	}
	return nil
}

func (x *IPRangeInfo) GetDetectionMethod() string {
	if x != nil {
		return x.DetectionMethod
	}
	return ""
}

func (x *IPRangeInfo) GetDetectedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DetectedAt
	}
	return nil
}

// 获取IP段响应
type GetIPRangesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	IpRanges      []*IPRangeInfo         `protobuf:"bytes,3,rep,name=ip_ranges,json=ipRanges,proto3" json:"ip_ranges,omitempty"`
	TotalRanges   int32                  `protobuf:"varint,4,opt,name=total_ranges,json=totalRanges,proto3" json:"total_ranges,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIPRangesResponse) Reset() {
	*x = GetIPRangesResponse{}
	mi := &file_proto_backend_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIPRangesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIPRangesResponse) ProtoMessage() {}

func (x *GetIPRangesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_backend_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIPRangesResponse.ProtoReflect.Descriptor instead.
func (*GetIPRangesResponse) Descriptor() ([]byte, []int) {
	return file_proto_backend_proto_rawDescGZIP(), []int{22}
}

func (x *GetIPRangesResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetIPRangesResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetIPRangesResponse) GetIpRanges() []*IPRangeInfo {
	if x != nil {
		return x.IpRanges
	}
	return nil
}

func (x *GetIPRangesResponse) GetTotalRanges() int32 {
	if x != nil {
		return x.TotalRanges
	}
	return 0
}

// 测试Agent请求
type TestAgentRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AgentId        string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	TestType       string                 `protobuf:"bytes,2,opt,name=test_type,json=testType,proto3" json:"test_type,omitempty"` // connection, proxy, all
	TimeoutSeconds int32                  `protobuf:"varint,3,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TestAgentRequest) Reset() {
	*x = TestAgentRequest{}
	mi := &file_proto_backend_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestAgentRequest) ProtoMessage() {}

func (x *TestAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_backend_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestAgentRequest.ProtoReflect.Descriptor instead.
func (*TestAgentRequest) Descriptor() ([]byte, []int) {
	return file_proto_backend_proto_rawDescGZIP(), []int{23}
}

func (x *TestAgentRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *TestAgentRequest) GetTestType() string {
	if x != nil {
		return x.TestType
	}
	return ""
}

func (x *TestAgentRequest) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

// 测试结果
type TestResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TestType      string                 `protobuf:"bytes,1,opt,name=test_type,json=testType,proto3" json:"test_type,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	LatencyMs     float64                `protobuf:"fixed64,4,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	TestedAt      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=tested_at,json=testedAt,proto3" json:"tested_at,omitempty"`
	Details       map[string]string      `protobuf:"bytes,6,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestResult) Reset() {
	*x = TestResult{}
	mi := &file_proto_backend_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestResult) ProtoMessage() {}

func (x *TestResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_backend_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestResult.ProtoReflect.Descriptor instead.
func (*TestResult) Descriptor() ([]byte, []int) {
	return file_proto_backend_proto_rawDescGZIP(), []int{24}
}

func (x *TestResult) GetTestType() string {
	if x != nil {
		return x.TestType
	}
	return ""
}

func (x *TestResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TestResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TestResult) GetLatencyMs() float64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *TestResult) GetTestedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.TestedAt
	}
	return nil
}

func (x *TestResult) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

// 测试Agent响应
type TestAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	TestResults   []*TestResult          `protobuf:"bytes,3,rep,name=test_results,json=testResults,proto3" json:"test_results,omitempty"`
	OverallStatus string                 `protobuf:"bytes,4,opt,name=overall_status,json=overallStatus,proto3" json:"overall_status,omitempty"` // healthy, degraded, failed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestAgentResponse) Reset() {
	*x = TestAgentResponse{}
	mi := &file_proto_backend_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestAgentResponse) ProtoMessage() {}

func (x *TestAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_backend_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestAgentResponse.ProtoReflect.Descriptor instead.
func (*TestAgentResponse) Descriptor() ([]byte, []int) {
	return file_proto_backend_proto_rawDescGZIP(), []int{25}
}

func (x *TestAgentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TestAgentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TestAgentResponse) GetTestResults() []*TestResult {
	if x != nil {
		return x.TestResults
	}
	return nil
}

func (x *TestAgentResponse) GetOverallStatus() string {
	if x != nil {
		return x.OverallStatus
	}
	return ""
}

// 获取协议支持信息请求
type GetProtocolInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"` // 可选，获取特定Agent的协议支持
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProtocolInfoRequest) Reset() {
	*x = GetProtocolInfoRequest{}
	mi := &file_proto_backend_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProtocolInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProtocolInfoRequest) ProtoMessage() {}

func (x *GetProtocolInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_backend_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProtocolInfoRequest.ProtoReflect.Descriptor instead.
func (*GetProtocolInfoRequest) Descriptor() ([]byte, []int) {
	return file_proto_backend_proto_rawDescGZIP(), []int{26}
}

func (x *GetProtocolInfoRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

// 协议支持信息
type ProtocolSupportInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProtocolName  string                 `protobuf:"bytes,1,opt,name=protocol_name,json=protocolName,proto3" json:"protocol_name,omitempty"` // HTTP, SOCKS5, Shadowsocks, VMess, Trojan, VLESS
	Supported     bool                   `protobuf:"varint,2,opt,name=supported,proto3" json:"supported,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Capabilities  map[string]string      `protobuf:"bytes,4,rep,name=capabilities,proto3" json:"capabilities,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Enabled       bool                   `protobuf:"varint,5,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtocolSupportInfo) Reset() {
	*x = ProtocolSupportInfo{}
	mi := &file_proto_backend_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtocolSupportInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtocolSupportInfo) ProtoMessage() {}

func (x *ProtocolSupportInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_backend_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtocolSupportInfo.ProtoReflect.Descriptor instead.
func (*ProtocolSupportInfo) Descriptor() ([]byte, []int) {
	return file_proto_backend_proto_rawDescGZIP(), []int{27}
}

func (x *ProtocolSupportInfo) GetProtocolName() string {
	if x != nil {
		return x.ProtocolName
	}
	return ""
}

func (x *ProtocolSupportInfo) GetSupported() bool {
	if x != nil {
		return x.Supported
	}
	return false
}

func (x *ProtocolSupportInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ProtocolSupportInfo) GetCapabilities() map[string]string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *ProtocolSupportInfo) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

// 获取协议支持信息响应
type GetProtocolInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Protocols     []*ProtocolSupportInfo `protobuf:"bytes,3,rep,name=protocols,proto3" json:"protocols,omitempty"`
	SystemVersion string                 `protobuf:"bytes,4,opt,name=system_version,json=systemVersion,proto3" json:"system_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProtocolInfoResponse) Reset() {
	*x = GetProtocolInfoResponse{}
	mi := &file_proto_backend_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProtocolInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProtocolInfoResponse) ProtoMessage() {}

func (x *GetProtocolInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_backend_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProtocolInfoResponse.ProtoReflect.Descriptor instead.
func (*GetProtocolInfoResponse) Descriptor() ([]byte, []int) {
	return file_proto_backend_proto_rawDescGZIP(), []int{28}
}

func (x *GetProtocolInfoResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetProtocolInfoResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetProtocolInfoResponse) GetProtocols() []*ProtocolSupportInfo {
	if x != nil {
		return x.Protocols
	}
	return nil
}

func (x *GetProtocolInfoResponse) GetSystemVersion() string {
	if x != nil {
		return x.SystemVersion
	}
	return ""
}

var File_proto_backend_proto protoreflect.FileDescriptor

const file_proto_backend_proto_rawDesc = "" +
	"\n" +
	"\x13proto/backend.proto\x12\abackend\x1a\x1fgoogle/protobuf/timestamp.proto\"\x14\n" +
	"\x12HealthCheckRequest\"\x9b\x01\n" +
	"\x13HealthCheckResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x18\n" +
	"\aservice\x18\x03 \x01(\tR\aservice\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\xb4\x01\n" +
	"\x10GetAgentsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12#\n" +
	"\rstatus_filter\x18\x03 \x01(\tR\fstatusFilter\x12%\n" +
	"\x0ecountry_filter\x18\x04 \x01(\tR\rcountryFilter\x12#\n" +
	"\rregion_filter\x18\x05 \x01(\tR\fregionFilter\"\xcb\x05\n" +
	"\tAgentInfo\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x03 \x01(\tR\tipAddress\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x18\n" +
	"\acountry\x18\x05 \x01(\tR\acountry\x12\x16\n" +
	"\x06region\x18\x06 \x01(\tR\x06region\x12\x12\n" +
	"\x04city\x18\a \x01(\tR\x04city\x12/\n" +
	"\x13current_connections\x18\b \x01(\x05R\x12currentConnections\x12\x1b\n" +
	"\tcpu_usage\x18\t \x01(\x01R\bcpuUsage\x12!\n" +
	"\fmemory_usage\x18\n" +
	" \x01(\x01R\vmemoryUsage\x12\x1d\n" +
	"\n" +
	"disk_usage\x18\v \x01(\x01R\tdiskUsage\x12'\n" +
	"\x0fnetwork_latency\x18\f \x01(\x05R\x0enetworkLatency\x12A\n" +
	"\x0elast_heartbeat\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\rlastHeartbeat\x12?\n" +
	"\rregistered_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\fregisteredAt\x12\x18\n" +
	"\aversion\x18\x0f \x01(\tR\aversion\x12<\n" +
	"\bmetadata\x18\x10 \x03(\v2 .backend.AgentInfo.MetadataEntryR\bmetadata\x128\n" +
	"\rip_range_info\x18\x11 \x01(\v2\x14.backend.IPRangeInfoR\vipRangeInfo\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc5\x01\n" +
	"\x11GetAgentsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12*\n" +
	"\x06agents\x18\x03 \x03(\v2\x12.backend.AgentInfoR\x06agents\x12\x1f\n" +
	"\vtotal_count\x18\x04 \x01(\x05R\n" +
	"totalCount\x12\x12\n" +
	"\x04page\x18\x05 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x06 \x01(\x05R\bpageSize\",\n" +
	"\x0fGetAgentRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\"p\n" +
	"\x10GetAgentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12(\n" +
	"\x05agent\x18\x03 \x01(\v2\x12.backend.AgentInfoR\x05agent\"\x16\n" +
	"\x14GetAgentStatsRequest\"\xcd\x04\n" +
	"\n" +
	"AgentStats\x12!\n" +
	"\ftotal_agents\x18\x01 \x01(\x05R\vtotalAgents\x12#\n" +
	"\ronline_agents\x18\x02 \x01(\x05R\fonlineAgents\x12%\n" +
	"\x0eoffline_agents\x18\x03 \x01(\x05R\rofflineAgents\x12%\n" +
	"\x0eunknown_agents\x18\x04 \x01(\x05R\runknownAgents\x12\"\n" +
	"\ravg_cpu_usage\x18\x05 \x01(\x01R\vavgCpuUsage\x12(\n" +
	"\x10avg_memory_usage\x18\x06 \x01(\x01R\x0eavgMemoryUsage\x12+\n" +
	"\x11total_connections\x18\a \x01(\x05R\x10totalConnections\x12T\n" +
	"\x11agents_by_country\x18\b \x03(\v2(.backend.AgentStats.AgentsByCountryEntryR\x0fagentsByCountry\x12Q\n" +
	"\x10agents_by_region\x18\t \x03(\v2'.backend.AgentStats.AgentsByRegionEntryR\x0eagentsByRegion\x1aB\n" +
	"\x14AgentsByCountryEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\x1aA\n" +
	"\x13AgentsByRegionEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"v\n" +
	"\x15GetAgentStatsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12)\n" +
	"\x05stats\x18\x03 \x01(\v2\x13.backend.AgentStatsR\x05stats\"\xd6\x02\n" +
	"\x12DeployAgentRequest\x12\x17\n" +
	"\anode_ip\x18\x01 \x01(\tR\x06nodeIp\x12\x19\n" +
	"\bssh_port\x18\x02 \x01(\x05R\asshPort\x12\x19\n" +
	"\bssh_user\x18\x03 \x01(\tR\asshUser\x12!\n" +
	"\fssh_password\x18\x04 \x01(\tR\vsshPassword\x12%\n" +
	"\x0econtroller_url\x18\x05 \x01(\tR\rcontrollerUrl\x12a\n" +
	"\x12deployment_options\x18\x06 \x03(\v22.backend.DeployAgentRequest.DeploymentOptionsEntryR\x11deploymentOptions\x1aD\n" +
	"\x16DeploymentOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc3\x01\n" +
	"\x13DeployAgentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x19\n" +
	"\bagent_id\x18\x03 \x01(\tR\aagentId\x12%\n" +
	"\x0edeployment_log\x18\x04 \x01(\tR\rdeploymentLog\x126\n" +
	"\x17deployment_time_seconds\x18\x05 \x01(\x05R\x15deploymentTimeSeconds\"\x9c\x01\n" +
	"\x15UninstallAgentRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12'\n" +
	"\x0fforce_uninstall\x18\x02 \x01(\bR\x0eforceUninstall\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12'\n" +
	"\x0ftimeout_seconds\x18\x04 \x01(\x05R\x0etimeoutSeconds\"\xc4\x01\n" +
	"\x16UninstallAgentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12)\n" +
	"\x10uninstall_status\x18\x03 \x01(\tR\x0funinstallStatus\x12#\n" +
	"\rcleaned_files\x18\x04 \x03(\tR\fcleanedFiles\x12&\n" +
	"\x0fcleanup_time_ms\x18\x05 \x01(\x03R\rcleanupTimeMs\"\xc7\x01\n" +
	"\x18UpdateAgentConfigRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1f\n" +
	"\vconfig_type\x18\x02 \x01(\tR\n" +
	"configType\x12%\n" +
	"\x0econfig_content\x18\x03 \x01(\tR\rconfigContent\x12!\n" +
	"\fforce_update\x18\x04 \x01(\bR\vforceUpdate\x12%\n" +
	"\x0econfig_version\x18\x05 \x01(\tR\rconfigVersion\"\xb3\x01\n" +
	"\x19UpdateAgentConfigResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12'\n" +
	"\x0fapplied_version\x18\x03 \x01(\tR\x0eappliedVersion\x129\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"a\n" +
	"\x19GetAgentMonitoringRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12)\n" +
	"\x10duration_minutes\x18\x02 \x01(\x05R\x0fdurationMinutes\"e\n" +
	"\x13MonitoringDataPoint\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value\"\xf9\x03\n" +
	"\x13AgentMonitoringData\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x129\n" +
	"\tcpu_usage\x18\x02 \x03(\v2\x1c.backend.MonitoringDataPointR\bcpuUsage\x12?\n" +
	"\fmemory_usage\x18\x03 \x03(\v2\x1c.backend.MonitoringDataPointR\vmemoryUsage\x12;\n" +
	"\n" +
	"disk_usage\x18\x04 \x03(\v2\x1c.backend.MonitoringDataPointR\tdiskUsage\x12M\n" +
	"\x13network_connections\x18\x05 \x03(\v2\x1c.backend.MonitoringDataPointR\x12networkConnections\x12%\n" +
	"\x0esingbox_status\x18\x06 \x01(\tR\rsingboxStatus\x12;\n" +
	"\vlast_update\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastUpdate\x12-\n" +
	"\x12active_connections\x18\b \x01(\x05R\x11activeConnections\x12,\n" +
	"\x12network_latency_ms\x18\t \x01(\x01R\x10networkLatencyMs\"\x97\x01\n" +
	"\x1aGetAgentMonitoringResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12E\n" +
	"\x0fmonitoring_data\x18\x03 \x01(\v2\x1c.backend.AgentMonitoringDataR\x0emonitoringData\"\xa6\x01\n" +
	"\x12GetIPRangesRequest\x12%\n" +
	"\x0ecountry_filter\x18\x01 \x01(\tR\rcountryFilter\x12#\n" +
	"\rregion_filter\x18\x02 \x01(\tR\fregionFilter\x12\x1d\n" +
	"\n" +
	"isp_filter\x18\x03 \x01(\tR\tispFilter\x12%\n" +
	"\x0einclude_agents\x18\x04 \x01(\bR\rincludeAgents\"\xb5\x02\n" +
	"\vIPRangeInfo\x12\x19\n" +
	"\bip_range\x18\x01 \x01(\tR\aipRange\x12\x18\n" +
	"\acountry\x18\x02 \x01(\tR\acountry\x12\x16\n" +
	"\x06region\x18\x03 \x01(\tR\x06region\x12\x12\n" +
	"\x04city\x18\x04 \x01(\tR\x04city\x12\x10\n" +
	"\x03isp\x18\x05 \x01(\tR\x03isp\x12\x1f\n" +
	"\vagent_count\x18\x06 \x01(\x05R\n" +
	"agentCount\x12*\n" +
	"\x06agents\x18\a \x03(\v2\x12.backend.AgentInfoR\x06agents\x12)\n" +
	"\x10detection_method\x18\b \x01(\tR\x0fdetectionMethod\x12;\n" +
	"\vdetected_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"detectedAt\"\x9f\x01\n" +
	"\x13GetIPRangesResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x121\n" +
	"\tip_ranges\x18\x03 \x03(\v2\x14.backend.IPRangeInfoR\bipRanges\x12!\n" +
	"\ftotal_ranges\x18\x04 \x01(\x05R\vtotalRanges\"s\n" +
	"\x10TestAgentRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1b\n" +
	"\ttest_type\x18\x02 \x01(\tR\btestType\x12'\n" +
	"\x0ftimeout_seconds\x18\x03 \x01(\x05R\x0etimeoutSeconds\"\xad\x02\n" +
	"\n" +
	"TestResult\x12\x1b\n" +
	"\ttest_type\x18\x01 \x01(\tR\btestType\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x04 \x01(\x01R\tlatencyMs\x127\n" +
	"\ttested_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\btestedAt\x12:\n" +
	"\adetails\x18\x06 \x03(\v2 .backend.TestResult.DetailsEntryR\adetails\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa6\x01\n" +
	"\x11TestAgentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x126\n" +
	"\ftest_results\x18\x03 \x03(\v2\x13.backend.TestResultR\vtestResults\x12%\n" +
	"\x0eoverall_status\x18\x04 \x01(\tR\roverallStatus\"3\n" +
	"\x16GetProtocolInfoRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\"\xa1\x02\n" +
	"\x13ProtocolSupportInfo\x12#\n" +
	"\rprotocol_name\x18\x01 \x01(\tR\fprotocolName\x12\x1c\n" +
	"\tsupported\x18\x02 \x01(\bR\tsupported\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12R\n" +
	"\fcapabilities\x18\x04 \x03(\v2..backend.ProtocolSupportInfo.CapabilitiesEntryR\fcapabilities\x12\x18\n" +
	"\aenabled\x18\x05 \x01(\bR\aenabled\x1a?\n" +
	"\x11CapabilitiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb0\x01\n" +
	"\x17GetProtocolInfoResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12:\n" +
	"\tprotocols\x18\x03 \x03(\v2\x1c.backend.ProtocolSupportInfoR\tprotocols\x12%\n" +
	"\x0esystem_version\x18\x04 \x01(\tR\rsystemVersion2\xeb\x06\n" +
	"\x0eBackendService\x12H\n" +
	"\vHealthCheck\x12\x1b.backend.HealthCheckRequest\x1a\x1c.backend.HealthCheckResponse\x12B\n" +
	"\tGetAgents\x12\x19.backend.GetAgentsRequest\x1a\x1a.backend.GetAgentsResponse\x12?\n" +
	"\bGetAgent\x12\x18.backend.GetAgentRequest\x1a\x19.backend.GetAgentResponse\x12N\n" +
	"\rGetAgentStats\x12\x1d.backend.GetAgentStatsRequest\x1a\x1e.backend.GetAgentStatsResponse\x12H\n" +
	"\vDeployAgent\x12\x1b.backend.DeployAgentRequest\x1a\x1c.backend.DeployAgentResponse\x12Q\n" +
	"\x0eUninstallAgent\x12\x1e.backend.UninstallAgentRequest\x1a\x1f.backend.UninstallAgentResponse\x12Z\n" +
	"\x11UpdateAgentConfig\x12!.backend.UpdateAgentConfigRequest\x1a\".backend.UpdateAgentConfigResponse\x12]\n" +
	"\x12GetAgentMonitoring\x12\".backend.GetAgentMonitoringRequest\x1a#.backend.GetAgentMonitoringResponse\x12H\n" +
	"\vGetIPRanges\x12\x1b.backend.GetIPRangesRequest\x1a\x1c.backend.GetIPRangesResponse\x12B\n" +
	"\tTestAgent\x12\x19.backend.TestAgentRequest\x1a\x1a.backend.TestAgentResponse\x12T\n" +
	"\x0fGetProtocolInfo\x12\x1f.backend.GetProtocolInfoRequest\x1a .backend.GetProtocolInfoResponseB0Z.github.com/xbox/sing-box-manager/proto/backendb\x06proto3"

var (
	file_proto_backend_proto_rawDescOnce sync.Once
	file_proto_backend_proto_rawDescData []byte
)

func file_proto_backend_proto_rawDescGZIP() []byte {
	file_proto_backend_proto_rawDescOnce.Do(func() {
		file_proto_backend_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_backend_proto_rawDesc), len(file_proto_backend_proto_rawDesc)))
	})
	return file_proto_backend_proto_rawDescData
}

var file_proto_backend_proto_msgTypes = make([]protoimpl.MessageInfo, 35)
var file_proto_backend_proto_goTypes = []any{
	(*HealthCheckRequest)(nil),         // 0: backend.HealthCheckRequest
	(*HealthCheckResponse)(nil),        // 1: backend.HealthCheckResponse
	(*GetAgentsRequest)(nil),           // 2: backend.GetAgentsRequest
	(*AgentInfo)(nil),                  // 3: backend.AgentInfo
	(*GetAgentsResponse)(nil),          // 4: backend.GetAgentsResponse
	(*GetAgentRequest)(nil),            // 5: backend.GetAgentRequest
	(*GetAgentResponse)(nil),           // 6: backend.GetAgentResponse
	(*GetAgentStatsRequest)(nil),       // 7: backend.GetAgentStatsRequest
	(*AgentStats)(nil),                 // 8: backend.AgentStats
	(*GetAgentStatsResponse)(nil),      // 9: backend.GetAgentStatsResponse
	(*DeployAgentRequest)(nil),         // 10: backend.DeployAgentRequest
	(*DeployAgentResponse)(nil),        // 11: backend.DeployAgentResponse
	(*UninstallAgentRequest)(nil),      // 12: backend.UninstallAgentRequest
	(*UninstallAgentResponse)(nil),     // 13: backend.UninstallAgentResponse
	(*UpdateAgentConfigRequest)(nil),   // 14: backend.UpdateAgentConfigRequest
	(*UpdateAgentConfigResponse)(nil),  // 15: backend.UpdateAgentConfigResponse
	(*GetAgentMonitoringRequest)(nil),  // 16: backend.GetAgentMonitoringRequest
	(*MonitoringDataPoint)(nil),        // 17: backend.MonitoringDataPoint
	(*AgentMonitoringData)(nil),        // 18: backend.AgentMonitoringData
	(*GetAgentMonitoringResponse)(nil), // 19: backend.GetAgentMonitoringResponse
	(*GetIPRangesRequest)(nil),         // 20: backend.GetIPRangesRequest
	(*IPRangeInfo)(nil),                // 21: backend.IPRangeInfo
	(*GetIPRangesResponse)(nil),        // 22: backend.GetIPRangesResponse
	(*TestAgentRequest)(nil),           // 23: backend.TestAgentRequest
	(*TestResult)(nil),                 // 24: backend.TestResult
	(*TestAgentResponse)(nil),          // 25: backend.TestAgentResponse
	(*GetProtocolInfoRequest)(nil),     // 26: backend.GetProtocolInfoRequest
	(*ProtocolSupportInfo)(nil),        // 27: backend.ProtocolSupportInfo
	(*GetProtocolInfoResponse)(nil),    // 28: backend.GetProtocolInfoResponse
	nil,                                // 29: backend.AgentInfo.MetadataEntry
	nil,                                // 30: backend.AgentStats.AgentsByCountryEntry
	nil,                                // 31: backend.AgentStats.AgentsByRegionEntry
	nil,                                // 32: backend.DeployAgentRequest.DeploymentOptionsEntry
	nil,                                // 33: backend.TestResult.DetailsEntry
	nil,                                // 34: backend.ProtocolSupportInfo.CapabilitiesEntry
	(*timestamppb.Timestamp)(nil),      // 35: google.protobuf.Timestamp
}
var file_proto_backend_proto_depIdxs = []int32{
	35, // 0: backend.HealthCheckResponse.timestamp:type_name -> google.protobuf.Timestamp
	35, // 1: backend.AgentInfo.last_heartbeat:type_name -> google.protobuf.Timestamp
	35, // 2: backend.AgentInfo.registered_at:type_name -> google.protobuf.Timestamp
	29, // 3: backend.AgentInfo.metadata:type_name -> backend.AgentInfo.MetadataEntry
	21, // 4: backend.AgentInfo.ip_range_info:type_name -> backend.IPRangeInfo
	3,  // 5: backend.GetAgentsResponse.agents:type_name -> backend.AgentInfo
	3,  // 6: backend.GetAgentResponse.agent:type_name -> backend.AgentInfo
	30, // 7: backend.AgentStats.agents_by_country:type_name -> backend.AgentStats.AgentsByCountryEntry
	31, // 8: backend.AgentStats.agents_by_region:type_name -> backend.AgentStats.AgentsByRegionEntry
	8,  // 9: backend.GetAgentStatsResponse.stats:type_name -> backend.AgentStats
	32, // 10: backend.DeployAgentRequest.deployment_options:type_name -> backend.DeployAgentRequest.DeploymentOptionsEntry
	35, // 11: backend.UpdateAgentConfigResponse.updated_at:type_name -> google.protobuf.Timestamp
	35, // 12: backend.MonitoringDataPoint.timestamp:type_name -> google.protobuf.Timestamp
	17, // 13: backend.AgentMonitoringData.cpu_usage:type_name -> backend.MonitoringDataPoint
	17, // 14: backend.AgentMonitoringData.memory_usage:type_name -> backend.MonitoringDataPoint
	17, // 15: backend.AgentMonitoringData.disk_usage:type_name -> backend.MonitoringDataPoint
	17, // 16: backend.AgentMonitoringData.network_connections:type_name -> backend.MonitoringDataPoint
	35, // 17: backend.AgentMonitoringData.last_update:type_name -> google.protobuf.Timestamp
	18, // 18: backend.GetAgentMonitoringResponse.monitoring_data:type_name -> backend.AgentMonitoringData
	3,  // 19: backend.IPRangeInfo.agents:type_name -> backend.AgentInfo
	35, // 20: backend.IPRangeInfo.detected_at:type_name -> google.protobuf.Timestamp
	21, // 21: backend.GetIPRangesResponse.ip_ranges:type_name -> backend.IPRangeInfo
	35, // 22: backend.TestResult.tested_at:type_name -> google.protobuf.Timestamp
	33, // 23: backend.TestResult.details:type_name -> backend.TestResult.DetailsEntry
	24, // 24: backend.TestAgentResponse.test_results:type_name -> backend.TestResult
	34, // 25: backend.ProtocolSupportInfo.capabilities:type_name -> backend.ProtocolSupportInfo.CapabilitiesEntry
	27, // 26: backend.GetProtocolInfoResponse.protocols:type_name -> backend.ProtocolSupportInfo
	0,  // 27: backend.BackendService.HealthCheck:input_type -> backend.HealthCheckRequest
	2,  // 28: backend.BackendService.GetAgents:input_type -> backend.GetAgentsRequest
	5,  // 29: backend.BackendService.GetAgent:input_type -> backend.GetAgentRequest
	7,  // 30: backend.BackendService.GetAgentStats:input_type -> backend.GetAgentStatsRequest
	10, // 31: backend.BackendService.DeployAgent:input_type -> backend.DeployAgentRequest
	12, // 32: backend.BackendService.UninstallAgent:input_type -> backend.UninstallAgentRequest
	14, // 33: backend.BackendService.UpdateAgentConfig:input_type -> backend.UpdateAgentConfigRequest
	16, // 34: backend.BackendService.GetAgentMonitoring:input_type -> backend.GetAgentMonitoringRequest
	20, // 35: backend.BackendService.GetIPRanges:input_type -> backend.GetIPRangesRequest
	23, // 36: backend.BackendService.TestAgent:input_type -> backend.TestAgentRequest
	26, // 37: backend.BackendService.GetProtocolInfo:input_type -> backend.GetProtocolInfoRequest
	1,  // 38: backend.BackendService.HealthCheck:output_type -> backend.HealthCheckResponse
	4,  // 39: backend.BackendService.GetAgents:output_type -> backend.GetAgentsResponse
	6,  // 40: backend.BackendService.GetAgent:output_type -> backend.GetAgentResponse
	9,  // 41: backend.BackendService.GetAgentStats:output_type -> backend.GetAgentStatsResponse
	11, // 42: backend.BackendService.DeployAgent:output_type -> backend.DeployAgentResponse
	13, // 43: backend.BackendService.UninstallAgent:output_type -> backend.UninstallAgentResponse
	15, // 44: backend.BackendService.UpdateAgentConfig:output_type -> backend.UpdateAgentConfigResponse
	19, // 45: backend.BackendService.GetAgentMonitoring:output_type -> backend.GetAgentMonitoringResponse
	22, // 46: backend.BackendService.GetIPRanges:output_type -> backend.GetIPRangesResponse
	25, // 47: backend.BackendService.TestAgent:output_type -> backend.TestAgentResponse
	28, // 48: backend.BackendService.GetProtocolInfo:output_type -> backend.GetProtocolInfoResponse
	38, // [38:49] is the sub-list for method output_type
	27, // [27:38] is the sub-list for method input_type
	27, // [27:27] is the sub-list for extension type_name
	27, // [27:27] is the sub-list for extension extendee
	0,  // [0:27] is the sub-list for field type_name
}

func init() { file_proto_backend_proto_init() }
func file_proto_backend_proto_init() {
	if File_proto_backend_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_backend_proto_rawDesc), len(file_proto_backend_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   35,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_backend_proto_goTypes,
		DependencyIndexes: file_proto_backend_proto_depIdxs,
		MessageInfos:      file_proto_backend_proto_msgTypes,
	}.Build()
	File_proto_backend_proto = out.File
	file_proto_backend_proto_goTypes = nil
	file_proto_backend_proto_depIdxs = nil
}
